// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Azapi
{
    public static class GetClientConfig
    {
        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Azapi = Pulumi.Azapi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var current = Azapi.GetClientConfig.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["subscriptionId"] = current.Apply(getClientConfigResult =&gt; getClientConfigResult.SubscriptionId),
        ///         ["tenantId"] = current.Apply(getClientConfigResult =&gt; getClientConfigResult.TenantId),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetClientConfigResult> InvokeAsync(GetClientConfigArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetClientConfigResult>("azapi:index/getClientConfig:getClientConfig", args ?? new GetClientConfigArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Azapi = Pulumi.Azapi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var current = Azapi.GetClientConfig.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["subscriptionId"] = current.Apply(getClientConfigResult =&gt; getClientConfigResult.SubscriptionId),
        ///         ["tenantId"] = current.Apply(getClientConfigResult =&gt; getClientConfigResult.TenantId),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetClientConfigResult> Invoke(GetClientConfigInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetClientConfigResult>("azapi:index/getClientConfig:getClientConfig", args ?? new GetClientConfigInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Azapi = Pulumi.Azapi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var current = Azapi.GetClientConfig.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["subscriptionId"] = current.Apply(getClientConfigResult =&gt; getClientConfigResult.SubscriptionId),
        ///         ["tenantId"] = current.Apply(getClientConfigResult =&gt; getClientConfigResult.TenantId),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetClientConfigResult> Invoke(GetClientConfigInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetClientConfigResult>("azapi:index/getClientConfig:getClientConfig", args ?? new GetClientConfigInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetClientConfigArgs : global::Pulumi.InvokeArgs
    {
        [Input("timeouts")]
        public Inputs.GetClientConfigTimeoutsArgs? Timeouts { get; set; }

        public GetClientConfigArgs()
        {
        }
        public static new GetClientConfigArgs Empty => new GetClientConfigArgs();
    }

    public sealed class GetClientConfigInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("timeouts")]
        public Input<Inputs.GetClientConfigTimeoutsInputArgs>? Timeouts { get; set; }

        public GetClientConfigInvokeArgs()
        {
        }
        public static new GetClientConfigInvokeArgs Empty => new GetClientConfigInvokeArgs();
    }


    [OutputType]
    public sealed class GetClientConfigResult
    {
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The object ID of the identity. E.g. `00000000-0000-0000-0000-000000000000`
        /// </summary>
        public readonly string ObjectId;
        /// <summary>
        /// The subscription ID. E.g. `00000000-0000-0000-0000-000000000000`
        /// </summary>
        public readonly string SubscriptionId;
        /// <summary>
        /// The resource ID of the subscription. E.g. `/subscriptions/00000000-0000-0000-0000-000000000000`
        /// </summary>
        public readonly string SubscriptionResourceId;
        /// <summary>
        /// The tenant ID. E.g. `00000000-0000-0000-0000-000000000000`
        /// </summary>
        public readonly string TenantId;
        public readonly Outputs.GetClientConfigTimeoutsResult? Timeouts;

        [OutputConstructor]
        private GetClientConfigResult(
            string id,

            string objectId,

            string subscriptionId,

            string subscriptionResourceId,

            string tenantId,

            Outputs.GetClientConfigTimeoutsResult? timeouts)
        {
            Id = id;
            ObjectId = objectId;
            SubscriptionId = subscriptionId;
            SubscriptionResourceId = subscriptionResourceId;
            TenantId = tenantId;
            Timeouts = timeouts;
        }
    }
}
