// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Azapi
{
    public static class GetResourceList
    {
        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Azapi = Pulumi.Azapi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var listBySubscription = Azapi.GetResourceList.Invoke(new()
        ///     {
        ///         ParentId = "/subscriptions/00000000-0000-0000-0000-000000000000",
        ///         ResponseExportValues = new[]
        ///         {
        ///             
        ///             {
        ///                 { "names", "value[].name" },
        ///                 { "values", "value[].{name: name, publicNetworkAccess: properties.publicNetworkAccess}" },
        ///             },
        ///         },
        ///         Type = "Microsoft.Automation/automationAccounts@2021-06-22",
        ///     });
        /// 
        ///     var listByResourceGroup = Azapi.GetResourceList.Invoke(new()
        ///     {
        ///         ParentId = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1",
        ///         ResponseExportValues = new[]
        ///         {
        ///             
        ///             {
        ///                 { "names", "value[].name" },
        ///             },
        ///         },
        ///         Type = "Microsoft.Automation/automationAccounts@2021-06-22",
        ///     });
        /// 
        ///     var listSubnetsByVnet = Azapi.GetResourceList.Invoke(new()
        ///     {
        ///         ParentId = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/vnet1",
        ///         ResponseExportValues = new[]
        ///         {
        ///             "*",
        ///         },
        ///         Type = "Microsoft.Network/virtualNetworks/subnets@2021-02-01",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetResourceListResult> InvokeAsync(GetResourceListArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetResourceListResult>("azapi:index/getResourceList:getResourceList", args ?? new GetResourceListArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Azapi = Pulumi.Azapi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var listBySubscription = Azapi.GetResourceList.Invoke(new()
        ///     {
        ///         ParentId = "/subscriptions/00000000-0000-0000-0000-000000000000",
        ///         ResponseExportValues = new[]
        ///         {
        ///             
        ///             {
        ///                 { "names", "value[].name" },
        ///                 { "values", "value[].{name: name, publicNetworkAccess: properties.publicNetworkAccess}" },
        ///             },
        ///         },
        ///         Type = "Microsoft.Automation/automationAccounts@2021-06-22",
        ///     });
        /// 
        ///     var listByResourceGroup = Azapi.GetResourceList.Invoke(new()
        ///     {
        ///         ParentId = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1",
        ///         ResponseExportValues = new[]
        ///         {
        ///             
        ///             {
        ///                 { "names", "value[].name" },
        ///             },
        ///         },
        ///         Type = "Microsoft.Automation/automationAccounts@2021-06-22",
        ///     });
        /// 
        ///     var listSubnetsByVnet = Azapi.GetResourceList.Invoke(new()
        ///     {
        ///         ParentId = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/vnet1",
        ///         ResponseExportValues = new[]
        ///         {
        ///             "*",
        ///         },
        ///         Type = "Microsoft.Network/virtualNetworks/subnets@2021-02-01",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetResourceListResult> Invoke(GetResourceListInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetResourceListResult>("azapi:index/getResourceList:getResourceList", args ?? new GetResourceListInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Azapi = Pulumi.Azapi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var listBySubscription = Azapi.GetResourceList.Invoke(new()
        ///     {
        ///         ParentId = "/subscriptions/00000000-0000-0000-0000-000000000000",
        ///         ResponseExportValues = new[]
        ///         {
        ///             
        ///             {
        ///                 { "names", "value[].name" },
        ///                 { "values", "value[].{name: name, publicNetworkAccess: properties.publicNetworkAccess}" },
        ///             },
        ///         },
        ///         Type = "Microsoft.Automation/automationAccounts@2021-06-22",
        ///     });
        /// 
        ///     var listByResourceGroup = Azapi.GetResourceList.Invoke(new()
        ///     {
        ///         ParentId = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1",
        ///         ResponseExportValues = new[]
        ///         {
        ///             
        ///             {
        ///                 { "names", "value[].name" },
        ///             },
        ///         },
        ///         Type = "Microsoft.Automation/automationAccounts@2021-06-22",
        ///     });
        /// 
        ///     var listSubnetsByVnet = Azapi.GetResourceList.Invoke(new()
        ///     {
        ///         ParentId = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/vnet1",
        ///         ResponseExportValues = new[]
        ///         {
        ///             "*",
        ///         },
        ///         Type = "Microsoft.Network/virtualNetworks/subnets@2021-02-01",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetResourceListResult> Invoke(GetResourceListInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetResourceListResult>("azapi:index/getResourceList:getResourceList", args ?? new GetResourceListInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetResourceListArgs : global::Pulumi.InvokeArgs
    {
        [Input("headers")]
        private Dictionary<string, string>? _headers;
        public Dictionary<string, string> Headers
        {
            get => _headers ?? (_headers = new Dictionary<string, string>());
            set => _headers = value;
        }

        [Input("parentId", required: true)]
        public string ParentId { get; set; } = null!;

        [Input("queryParameters")]
        private Dictionary<string, ImmutableArray<string>>? _queryParameters;
        public Dictionary<string, ImmutableArray<string>> QueryParameters
        {
            get => _queryParameters ?? (_queryParameters = new Dictionary<string, ImmutableArray<string>>());
            set => _queryParameters = value;
        }

        [Input("responseExportValues")]
        public object? ResponseExportValues { get; set; }

        [Input("retry")]
        public Inputs.GetResourceListRetryArgs? Retry { get; set; }

        [Input("timeouts")]
        public Inputs.GetResourceListTimeoutsArgs? Timeouts { get; set; }

        [Input("type", required: true)]
        public string Type { get; set; } = null!;

        public GetResourceListArgs()
        {
        }
        public static new GetResourceListArgs Empty => new GetResourceListArgs();
    }

    public sealed class GetResourceListInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("headers")]
        private InputMap<string>? _headers;
        public InputMap<string> Headers
        {
            get => _headers ?? (_headers = new InputMap<string>());
            set => _headers = value;
        }

        [Input("parentId", required: true)]
        public Input<string> ParentId { get; set; } = null!;

        [Input("queryParameters")]
        private InputMap<ImmutableArray<string>>? _queryParameters;
        public InputMap<ImmutableArray<string>> QueryParameters
        {
            get => _queryParameters ?? (_queryParameters = new InputMap<ImmutableArray<string>>());
            set => _queryParameters = value;
        }

        [Input("responseExportValues")]
        public Input<object>? ResponseExportValues { get; set; }

        [Input("retry")]
        public Input<Inputs.GetResourceListRetryInputArgs>? Retry { get; set; }

        [Input("timeouts")]
        public Input<Inputs.GetResourceListTimeoutsInputArgs>? Timeouts { get; set; }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public GetResourceListInvokeArgs()
        {
        }
        public static new GetResourceListInvokeArgs Empty => new GetResourceListInvokeArgs();
    }


    [OutputType]
    public sealed class GetResourceListResult
    {
        public readonly ImmutableDictionary<string, string>? Headers;
        public readonly string Id;
        public readonly object Output;
        public readonly string ParentId;
        public readonly ImmutableDictionary<string, ImmutableArray<string>>? QueryParameters;
        public readonly object? ResponseExportValues;
        public readonly Outputs.GetResourceListRetryResult? Retry;
        public readonly Outputs.GetResourceListTimeoutsResult? Timeouts;
        public readonly string Type;

        [OutputConstructor]
        private GetResourceListResult(
            ImmutableDictionary<string, string>? headers,

            string id,

            object output,

            string parentId,

            ImmutableDictionary<string, ImmutableArray<string>>? queryParameters,

            object? responseExportValues,

            Outputs.GetResourceListRetryResult? retry,

            Outputs.GetResourceListTimeoutsResult? timeouts,

            string type)
        {
            Headers = headers;
            Id = id;
            Output = output;
            ParentId = parentId;
            QueryParameters = queryParameters;
            ResponseExportValues = responseExportValues;
            Retry = retry;
            Timeouts = timeouts;
            Type = type;
        }
    }
}
