// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.azapi.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetResourceIdentity {
    /**
     * @return A list of User Managed Identity ID&#39;s which should be assigned to the azure resource.
     * 
     */
    private List<String> identityIds;
    /**
     * @return The Principal ID for the Service Principal associated with the Managed Service Identity of this azure resource.
     * 
     */
    private String principalId;
    /**
     * @return The Tenant ID for the Service Principal associated with the Managed Service Identity of this azure resource.
     * 
     */
    private String tenantId;
    /**
     * @return It is in a format like `&lt;resource-type&gt;@&lt;api-version&gt;`. `&lt;resource-type&gt;` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
     * `&lt;api-version&gt;` is version of the API used to manage this azure resource.
     * 
     */
    private String type;

    private GetResourceIdentity() {}
    /**
     * @return A list of User Managed Identity ID&#39;s which should be assigned to the azure resource.
     * 
     */
    public List<String> identityIds() {
        return this.identityIds;
    }
    /**
     * @return The Principal ID for the Service Principal associated with the Managed Service Identity of this azure resource.
     * 
     */
    public String principalId() {
        return this.principalId;
    }
    /**
     * @return The Tenant ID for the Service Principal associated with the Managed Service Identity of this azure resource.
     * 
     */
    public String tenantId() {
        return this.tenantId;
    }
    /**
     * @return It is in a format like `&lt;resource-type&gt;@&lt;api-version&gt;`. `&lt;resource-type&gt;` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
     * `&lt;api-version&gt;` is version of the API used to manage this azure resource.
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetResourceIdentity defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> identityIds;
        private String principalId;
        private String tenantId;
        private String type;
        public Builder() {}
        public Builder(GetResourceIdentity defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.identityIds = defaults.identityIds;
    	      this.principalId = defaults.principalId;
    	      this.tenantId = defaults.tenantId;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder identityIds(List<String> identityIds) {
            this.identityIds = Objects.requireNonNull(identityIds);
            return this;
        }
        public Builder identityIds(String... identityIds) {
            return identityIds(List.of(identityIds));
        }
        @CustomType.Setter
        public Builder principalId(String principalId) {
            this.principalId = Objects.requireNonNull(principalId);
            return this;
        }
        @CustomType.Setter
        public Builder tenantId(String tenantId) {
            this.tenantId = Objects.requireNonNull(tenantId);
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        public GetResourceIdentity build() {
            final var o = new GetResourceIdentity();
            o.identityIds = identityIds;
            o.principalId = principalId;
            o.tenantId = tenantId;
            o.type = type;
            return o;
        }
    }
}
