// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.azapi.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetResourceActionResult {
    private @Nullable String action;
    private @Nullable String body;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private @Nullable String method;
    /**
     * @return The output json containing the properties specified in `response_export_values`. Here are some examples to decode json and extract the value.
     * 
     */
    private String output;
    private @Nullable String resourceId;
    private @Nullable List<String> responseExportValues;
    private String type;

    private GetResourceActionResult() {}
    public Optional<String> action() {
        return Optional.ofNullable(this.action);
    }
    public Optional<String> body() {
        return Optional.ofNullable(this.body);
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public Optional<String> method() {
        return Optional.ofNullable(this.method);
    }
    /**
     * @return The output json containing the properties specified in `response_export_values`. Here are some examples to decode json and extract the value.
     * 
     */
    public String output() {
        return this.output;
    }
    public Optional<String> resourceId() {
        return Optional.ofNullable(this.resourceId);
    }
    public List<String> responseExportValues() {
        return this.responseExportValues == null ? List.of() : this.responseExportValues;
    }
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetResourceActionResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String action;
        private @Nullable String body;
        private String id;
        private @Nullable String method;
        private String output;
        private @Nullable String resourceId;
        private @Nullable List<String> responseExportValues;
        private String type;
        public Builder() {}
        public Builder(GetResourceActionResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.action = defaults.action;
    	      this.body = defaults.body;
    	      this.id = defaults.id;
    	      this.method = defaults.method;
    	      this.output = defaults.output;
    	      this.resourceId = defaults.resourceId;
    	      this.responseExportValues = defaults.responseExportValues;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder action(@Nullable String action) {
            this.action = action;
            return this;
        }
        @CustomType.Setter
        public Builder body(@Nullable String body) {
            this.body = body;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder method(@Nullable String method) {
            this.method = method;
            return this;
        }
        @CustomType.Setter
        public Builder output(String output) {
            this.output = Objects.requireNonNull(output);
            return this;
        }
        @CustomType.Setter
        public Builder resourceId(@Nullable String resourceId) {
            this.resourceId = resourceId;
            return this;
        }
        @CustomType.Setter
        public Builder responseExportValues(@Nullable List<String> responseExportValues) {
            this.responseExportValues = responseExportValues;
            return this;
        }
        public Builder responseExportValues(String... responseExportValues) {
            return responseExportValues(List.of(responseExportValues));
        }
        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        public GetResourceActionResult build() {
            final var o = new GetResourceActionResult();
            o.action = action;
            o.body = body;
            o.id = id;
            o.method = method;
            o.output = output;
            o.resourceId = resourceId;
            o.responseExportValues = responseExportValues;
            o.type = type;
            return o;
        }
    }
}
