// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace ediri.Azapi
{
    public static class Config
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("azapi");

        private static readonly __Value<ImmutableArray<string>> _auxiliaryTenantIds = new __Value<ImmutableArray<string>>(() => __config.GetObject<ImmutableArray<string>>("auxiliaryTenantIds"));
        public static ImmutableArray<string> AuxiliaryTenantIds
        {
            get => _auxiliaryTenantIds.Get();
            set => _auxiliaryTenantIds.Set(value);
        }

        private static readonly __Value<string?> _clientCertificatePassword = new __Value<string?>(() => __config.Get("clientCertificatePassword"));
        /// <summary>
        /// The password associated with the Client Certificate. For use when authenticating as a Service Principal using a Client
        /// Certificate
        /// </summary>
        public static string? ClientCertificatePassword
        {
            get => _clientCertificatePassword.Get();
            set => _clientCertificatePassword.Set(value);
        }

        private static readonly __Value<string?> _clientCertificatePath = new __Value<string?>(() => __config.Get("clientCertificatePath"));
        /// <summary>
        /// The path to the Client Certificate associated with the Service Principal for use when authenticating as a Service
        /// Principal using a Client Certificate.
        /// </summary>
        public static string? ClientCertificatePath
        {
            get => _clientCertificatePath.Get();
            set => _clientCertificatePath.Set(value);
        }

        private static readonly __Value<string?> _clientId = new __Value<string?>(() => __config.Get("clientId"));
        /// <summary>
        /// The Client ID which should be used.
        /// </summary>
        public static string? ClientId
        {
            get => _clientId.Get();
            set => _clientId.Set(value);
        }

        private static readonly __Value<string?> _clientSecret = new __Value<string?>(() => __config.Get("clientSecret"));
        /// <summary>
        /// The Client Secret which should be used. For use When authenticating as a Service Principal using a Client Secret.
        /// </summary>
        public static string? ClientSecret
        {
            get => _clientSecret.Get();
            set => _clientSecret.Set(value);
        }

        private static readonly __Value<string?> _customCorrelationRequestId = new __Value<string?>(() => __config.Get("customCorrelationRequestId"));
        /// <summary>
        /// The value of the x-ms-correlation-request-id header (otherwise an auto-generated UUID will be used).
        /// </summary>
        public static string? CustomCorrelationRequestId
        {
            get => _customCorrelationRequestId.Get();
            set => _customCorrelationRequestId.Set(value);
        }

        private static readonly __Value<string?> _defaultLocation = new __Value<string?>(() => __config.Get("defaultLocation"));
        public static string? DefaultLocation
        {
            get => _defaultLocation.Get();
            set => _defaultLocation.Set(value);
        }

        private static readonly __Value<string?> _defaultName = new __Value<string?>(() => __config.Get("defaultName"));
        public static string? DefaultName
        {
            get => _defaultName.Get();
            set => _defaultName.Set(value);
        }

        private static readonly __Value<string?> _defaultNamingPrefix = new __Value<string?>(() => __config.Get("defaultNamingPrefix"));
        public static string? DefaultNamingPrefix
        {
            get => _defaultNamingPrefix.Get();
            set => _defaultNamingPrefix.Set(value);
        }

        private static readonly __Value<string?> _defaultNamingSuffix = new __Value<string?>(() => __config.Get("defaultNamingSuffix"));
        public static string? DefaultNamingSuffix
        {
            get => _defaultNamingSuffix.Get();
            set => _defaultNamingSuffix.Set(value);
        }

        private static readonly __Value<ImmutableDictionary<string, string>?> _defaultTags = new __Value<ImmutableDictionary<string, string>?>(() => __config.GetObject<ImmutableDictionary<string, string>>("defaultTags"));
        public static ImmutableDictionary<string, string>? DefaultTags
        {
            get => _defaultTags.Get();
            set => _defaultTags.Set(value);
        }

        private static readonly __Value<bool?> _disableCorrelationRequestId = new __Value<bool?>(() => __config.GetBoolean("disableCorrelationRequestId"));
        /// <summary>
        /// This will disable the x-ms-correlation-request-id header.
        /// </summary>
        public static bool? DisableCorrelationRequestId
        {
            get => _disableCorrelationRequestId.Get();
            set => _disableCorrelationRequestId.Set(value);
        }

        private static readonly __Value<bool?> _disableTerraformPartnerId = new __Value<bool?>(() => __config.GetBoolean("disableTerraformPartnerId"));
        /// <summary>
        /// This will disable the Terraform Partner ID which is used if a custom `partner_id` isn't specified.
        /// </summary>
        public static bool? DisableTerraformPartnerId
        {
            get => _disableTerraformPartnerId.Get();
            set => _disableTerraformPartnerId.Set(value);
        }

        private static readonly __Value<string?> _environment = new __Value<string?>(() => __config.Get("environment"));
        /// <summary>
        /// The Cloud Environment which should be used. Possible values are public, usgovernment and china. Defaults to public.
        /// </summary>
        public static string? Environment
        {
            get => _environment.Get();
            set => _environment.Set(value);
        }

        private static readonly __Value<string?> _oidcRequestToken = new __Value<string?>(() => __config.Get("oidcRequestToken"));
        /// <summary>
        /// The bearer token for the request to the OIDC provider. For use When authenticating as a Service Principal using OpenID
        /// Connect.
        /// </summary>
        public static string? OidcRequestToken
        {
            get => _oidcRequestToken.Get();
            set => _oidcRequestToken.Set(value);
        }

        private static readonly __Value<string?> _oidcRequestUrl = new __Value<string?>(() => __config.Get("oidcRequestUrl"));
        /// <summary>
        /// The URL for the OIDC provider from which to request an ID token. For use When authenticating as a Service Principal
        /// using OpenID Connect.
        /// </summary>
        public static string? OidcRequestUrl
        {
            get => _oidcRequestUrl.Get();
            set => _oidcRequestUrl.Set(value);
        }

        private static readonly __Value<string?> _oidcToken = new __Value<string?>(() => __config.Get("oidcToken"));
        /// <summary>
        /// The OIDC ID token for use when authenticating as a Service Principal using OpenID Connect.
        /// </summary>
        public static string? OidcToken
        {
            get => _oidcToken.Get();
            set => _oidcToken.Set(value);
        }

        private static readonly __Value<string?> _oidcTokenFilePath = new __Value<string?>(() => __config.Get("oidcTokenFilePath"));
        /// <summary>
        /// The path to a file containing an OIDC ID token for use when authenticating as a Service Principal using OpenID Connect.
        /// </summary>
        public static string? OidcTokenFilePath
        {
            get => _oidcTokenFilePath.Get();
            set => _oidcTokenFilePath.Set(value);
        }

        private static readonly __Value<string?> _partnerId = new __Value<string?>(() => __config.Get("partnerId"));
        /// <summary>
        /// A GUID/UUID that is registered with Microsoft to facilitate partner resource usage attribution.
        /// </summary>
        public static string? PartnerId
        {
            get => _partnerId.Get();
            set => _partnerId.Set(value);
        }

        private static readonly __Value<bool?> _skipProviderRegistration = new __Value<bool?>(() => __config.GetBoolean("skipProviderRegistration"));
        /// <summary>
        /// Should the Provider skip registering all of the Resource Providers that it supports, if they're not already registered?
        /// </summary>
        public static bool? SkipProviderRegistration
        {
            get => _skipProviderRegistration.Get();
            set => _skipProviderRegistration.Set(value);
        }

        private static readonly __Value<string?> _subscriptionId = new __Value<string?>(() => __config.Get("subscriptionId"));
        /// <summary>
        /// The Subscription ID which should be used.
        /// </summary>
        public static string? SubscriptionId
        {
            get => _subscriptionId.Get();
            set => _subscriptionId.Set(value);
        }

        private static readonly __Value<string?> _tenantId = new __Value<string?>(() => __config.Get("tenantId"));
        /// <summary>
        /// The Tenant ID which should be used.
        /// </summary>
        public static string? TenantId
        {
            get => _tenantId.Get();
            set => _tenantId.Set(value);
        }

        private static readonly __Value<bool?> _useCli = new __Value<bool?>(() => __config.GetBoolean("useCli"));
        /// <summary>
        /// Allow Azure CLI to be used for Authentication.
        /// </summary>
        public static bool? UseCli
        {
            get => _useCli.Get();
            set => _useCli.Set(value);
        }

        private static readonly __Value<bool?> _useMsi = new __Value<bool?>(() => __config.GetBoolean("useMsi"));
        /// <summary>
        /// Allow Managed Service Identity to be used for Authentication.
        /// </summary>
        public static bool? UseMsi
        {
            get => _useMsi.Get();
            set => _useMsi.Set(value);
        }

        private static readonly __Value<bool?> _useOidc = new __Value<bool?>(() => __config.GetBoolean("useOidc"));
        /// <summary>
        /// Allow OpenID Connect to be used for authentication
        /// </summary>
        public static bool? UseOidc
        {
            get => _useOidc.Get();
            set => _useOidc.Set(value);
        }

    }
}
