// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/dirien/pulumi-azapi/sdk/go/azapi/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// List of auxiliary Tenant IDs required for multi-tenancy and cross-tenant scenarios. This can also be sourced from the
// `ARM_AUXILIARY_TENANT_IDS` Environment Variable.
func GetAuxiliaryTenantIds(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:auxiliaryTenantIds")
}

// A base64-encoded PKCS#12 bundle to be used as the client certificate for authentication. This can also be sourced from
// the `ARM_CLIENT_CERTIFICATE` environment variable.
func GetClientCertificate(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:clientCertificate")
}

// The password associated with the Client Certificate. This can also be sourced from the `ARM_CLIENT_CERTIFICATE_PASSWORD`
// Environment Variable.
func GetClientCertificatePassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:clientCertificatePassword")
}

// The path to the Client Certificate associated with the Service Principal which should be used. This can also be sourced
// from the `ARM_CLIENT_CERTIFICATE_PATH` Environment Variable.
func GetClientCertificatePath(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:clientCertificatePath")
}

// The Client ID which should be used. This can also be sourced from the `ARM_CLIENT_ID` Environment Variable.
func GetClientId(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:clientId")
}

// The path to a file containing the Client ID which should be used. This can also be sourced from the
// `ARM_CLIENT_ID_FILE_PATH` Environment Variable.
func GetClientIdFilePath(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:clientIdFilePath")
}

// The Client Secret which should be used. This can also be sourced from the `ARM_CLIENT_SECRET` Environment Variable.
func GetClientSecret(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:clientSecret")
}

// The path to a file containing the Client Secret which should be used. For use When authenticating as a Service Principal
// using a Client Secret. This can also be sourced from the `ARM_CLIENT_SECRET_FILE_PATH` Environment Variable.
func GetClientSecretFilePath(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:clientSecretFilePath")
}

// The value of the `x-ms-correlation-request-id` header, otherwise an auto-generated UUID will be used. This can also be
// sourced from the `ARM_CORRELATION_REQUEST_ID` environment variable.
func GetCustomCorrelationRequestId(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:customCorrelationRequestId")
}

// The default Azure Region where the azure resource should exist. The `location` in each resource block can override the
// `defaultLocation`. Changing this forces new resources to be created.
func GetDefaultLocation(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:defaultLocation")
}

// The default name to create the azure resource. The `name` in each resource block can override the `defaultName`.
// Changing this forces new resources to be created.
func GetDefaultName(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:defaultName")
}

// A mapping of tags which should be assigned to the azure resource as default tags. The`tags` in each resource block can
// override the `defaultTags`.
func GetDefaultTags(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:defaultTags")
}

// This will disable the x-ms-correlation-request-id header.
func GetDisableCorrelationRequestId(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "azapi:disableCorrelationRequestId")
}

// Disable default output. The default is false. When set to false, the provider will output the read-only properties if
// `responseExportValues` is not specified in the resource block. When set to true, the provider will disable this output.
// This can also be sourced from the `ARM_DISABLE_DEFAULT_OUTPUT` Environment Variable.
func GetDisableDefaultOutput(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "azapi:disableDefaultOutput")
}
func GetDisableTerraformPartnerId(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "azapi:disableTerraformPartnerId")
}

// Enable Preflight Validation. The default is false. When set to true, the provider will use Preflight to do static
// validation before really deploying a new resource. When set to false, the provider will disable this validation. This
// can also be sourced from the `ARM_ENABLE_PREFLIGHT` Environment Variable.
func GetEnablePreflight(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "azapi:enablePreflight")
}

// The Azure API Endpoint Configuration.
func GetEndpoints(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:endpoints")
}

// The Cloud Environment which should be used. Possible values are `public`, `usgovernment` and `china`. Defaults to
// `public`. This can also be sourced from the `ARM_ENVIRONMENT` Environment Variable.
func GetEnvironment(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:environment")
}

// The maximum number of retries to attempt if the Azure API returns an HTTP 408, 429, 500, 502, 503, or 504 response. The
// default is `3`. The resource-specific retry configuration may additionally be used to retry on other errors and
// conditions.
func GetMaximumBusyRetryAttempts(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "azapi:maximumBusyRetryAttempts")
}

// The Azure Pipelines Service Connection ID to use for authentication. This can also be sourced from the
// `ARM_ADO_PIPELINE_SERVICE_CONNECTION_ID` or `ARM_OIDC_AZURE_SERVICE_CONNECTION_ID` Environment Variables.
func GetOidcAzureServiceConnectionId(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:oidcAzureServiceConnectionId")
}

// The bearer token for the request to the OIDC provider. This can also be sourced from the `ARM_OIDC_REQUEST_TOKEN` or
// `ACTIONS_ID_TOKEN_REQUEST_TOKEN` Environment Variables.
func GetOidcRequestToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:oidcRequestToken")
}

// The URL for the OIDC provider from which to request an ID token. This can also be sourced from the
// `ARM_OIDC_REQUEST_URL` or `ACTIONS_ID_TOKEN_REQUEST_URL` Environment Variables.
func GetOidcRequestUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:oidcRequestUrl")
}

// The ID token when authenticating using OpenID Connect (OIDC). This can also be sourced from the `ARM_OIDC_TOKEN`
// environment Variable.
func GetOidcToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:oidcToken")
}

// The path to a file containing an ID token when authenticating using OpenID Connect (OIDC). This can also be sourced from
// the `ARM_OIDC_TOKEN_FILE_PATH` environment Variable.
func GetOidcTokenFilePath(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:oidcTokenFilePath")
}

// A GUID/UUID that is
// [registered](https://docs.microsoft.com/azure/marketplace/azure-partner-customer-usage-attribution#register-guids-and-offers)
// with Microsoft to facilitate partner resource usage attribution. This can also be sourced from the `ARM_PARTNER_ID`
// Environment Variable.
func GetPartnerId(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:partnerId")
}

// Should the Provider skip registering the Resource Providers it supports? This can also be sourced from the
// `ARM_SKIP_PROVIDER_REGISTRATION` Environment Variable. Defaults to `false`.
func GetSkipProviderRegistration(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "azapi:skipProviderRegistration")
}

// The Subscription ID which should be used. This can also be sourced from the `ARM_SUBSCRIPTION_ID` Environment Variable.
func GetSubscriptionId(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:subscriptionId")
}

// The Tenant ID should be used. This can also be sourced from the `ARM_TENANT_ID` Environment Variable.
func GetTenantId(ctx *pulumi.Context) string {
	return config.Get(ctx, "azapi:tenantId")
}

// Should AKS Workload Identity be used for Authentication? This can also be sourced from the
// `ARM_USE_AKS_WORKLOAD_IDENTITY` Environment Variable. Defaults to `false`. When set, `clientId`, `tenantId` and
// `oidcTokenFilePath` will be detected from the environment and do not need to be specified.
func GetUseAksWorkloadIdentity(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "azapi:useAksWorkloadIdentity")
}

// Should Azure CLI be used for authentication? This can also be sourced from the `ARM_USE_CLI` environment variable.
// Defaults to `true`.
func GetUseCli(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "azapi:useCli")
}

// Should Managed Identity be used for Authentication? This can also be sourced from the `ARM_USE_MSI` Environment
// Variable. Defaults to `false`.
func GetUseMsi(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "azapi:useMsi")
}

// Should OIDC be used for Authentication? This can also be sourced from the `ARM_USE_OIDC` Environment Variable. Defaults
// to `false`.
func GetUseOidc(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "azapi:useOidc")
}
