// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.azapi;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import io.dirien.azapi.Utilities;
import io.dirien.azapi.inputs.GetResourceActionArgs;
import io.dirien.azapi.inputs.GetResourceActionPlainArgs;
import io.dirien.azapi.inputs.GetResourceArgs;
import io.dirien.azapi.inputs.GetResourcePlainArgs;
import io.dirien.azapi.outputs.GetResourceActionResult;
import io.dirien.azapi.outputs.GetResourceResult;
import java.util.concurrent.CompletableFuture;

public final class AzapiFunctions {
    /**
     * This resource can access any existing Azure resource manager resource.
     * 
     */
    public static Output<GetResourceResult> getResource(GetResourceArgs args) {
        return getResource(args, InvokeOptions.Empty);
    }
    /**
     * This resource can access any existing Azure resource manager resource.
     * 
     */
    public static CompletableFuture<GetResourceResult> getResourcePlain(GetResourcePlainArgs args) {
        return getResourcePlain(args, InvokeOptions.Empty);
    }
    /**
     * This resource can access any existing Azure resource manager resource.
     * 
     */
    public static Output<GetResourceResult> getResource(GetResourceArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("azapi:index/getResource:getResource", TypeShape.of(GetResourceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This resource can access any existing Azure resource manager resource.
     * 
     */
    public static CompletableFuture<GetResourceResult> getResourcePlain(GetResourcePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("azapi:index/getResource:getResource", TypeShape.of(GetResourceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This resource can perform resource action which gets information from an existing resource.
     * It&#39;s recommended to use `azapi.ResourceAction` data source to perform readonly action, please use `azapi.ResourceAction` resource,
     * if user wants to perform actions which change a resource&#39;s state.
     * 
     * ## Example Usage
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.azure.core.ResourceGroup;
     * import com.pulumi.azure.core.ResourceGroupArgs;
     * import com.pulumi.azure.automation.Account;
     * import com.pulumi.azure.automation.AccountArgs;
     * import com.pulumi.azapi.AzapiFunctions;
     * import com.pulumi.azapi.inputs.GetResourceActionArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         var exampleResourceGroup = new ResourceGroup(&#34;exampleResourceGroup&#34;, ResourceGroupArgs.builder()        
     *             .location(&#34;west europe&#34;)
     *             .build());
     * 
     *         var exampleAccount = new Account(&#34;exampleAccount&#34;, AccountArgs.builder()        
     *             .resourceGroupName(exampleResourceGroup.name())
     *             .location(exampleResourceGroup.location())
     *             .skuName(&#34;Basic&#34;)
     *             .build());
     * 
     *         final var exampleResourceAction = AzapiFunctions.getResourceAction(GetResourceActionArgs.builder()
     *             .type(&#34;Microsoft.Automation/automationAccounts@2021-06-22&#34;)
     *             .resourceId(exampleAccount.id())
     *             .action(&#34;listKeys&#34;)
     *             .responseExportValues(&#34;*&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * 
     */
    public static Output<GetResourceActionResult> getResourceAction(GetResourceActionArgs args) {
        return getResourceAction(args, InvokeOptions.Empty);
    }
    /**
     * This resource can perform resource action which gets information from an existing resource.
     * It&#39;s recommended to use `azapi.ResourceAction` data source to perform readonly action, please use `azapi.ResourceAction` resource,
     * if user wants to perform actions which change a resource&#39;s state.
     * 
     * ## Example Usage
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.azure.core.ResourceGroup;
     * import com.pulumi.azure.core.ResourceGroupArgs;
     * import com.pulumi.azure.automation.Account;
     * import com.pulumi.azure.automation.AccountArgs;
     * import com.pulumi.azapi.AzapiFunctions;
     * import com.pulumi.azapi.inputs.GetResourceActionArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         var exampleResourceGroup = new ResourceGroup(&#34;exampleResourceGroup&#34;, ResourceGroupArgs.builder()        
     *             .location(&#34;west europe&#34;)
     *             .build());
     * 
     *         var exampleAccount = new Account(&#34;exampleAccount&#34;, AccountArgs.builder()        
     *             .resourceGroupName(exampleResourceGroup.name())
     *             .location(exampleResourceGroup.location())
     *             .skuName(&#34;Basic&#34;)
     *             .build());
     * 
     *         final var exampleResourceAction = AzapiFunctions.getResourceAction(GetResourceActionArgs.builder()
     *             .type(&#34;Microsoft.Automation/automationAccounts@2021-06-22&#34;)
     *             .resourceId(exampleAccount.id())
     *             .action(&#34;listKeys&#34;)
     *             .responseExportValues(&#34;*&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * 
     */
    public static CompletableFuture<GetResourceActionResult> getResourceActionPlain(GetResourceActionPlainArgs args) {
        return getResourceActionPlain(args, InvokeOptions.Empty);
    }
    /**
     * This resource can perform resource action which gets information from an existing resource.
     * It&#39;s recommended to use `azapi.ResourceAction` data source to perform readonly action, please use `azapi.ResourceAction` resource,
     * if user wants to perform actions which change a resource&#39;s state.
     * 
     * ## Example Usage
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.azure.core.ResourceGroup;
     * import com.pulumi.azure.core.ResourceGroupArgs;
     * import com.pulumi.azure.automation.Account;
     * import com.pulumi.azure.automation.AccountArgs;
     * import com.pulumi.azapi.AzapiFunctions;
     * import com.pulumi.azapi.inputs.GetResourceActionArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         var exampleResourceGroup = new ResourceGroup(&#34;exampleResourceGroup&#34;, ResourceGroupArgs.builder()        
     *             .location(&#34;west europe&#34;)
     *             .build());
     * 
     *         var exampleAccount = new Account(&#34;exampleAccount&#34;, AccountArgs.builder()        
     *             .resourceGroupName(exampleResourceGroup.name())
     *             .location(exampleResourceGroup.location())
     *             .skuName(&#34;Basic&#34;)
     *             .build());
     * 
     *         final var exampleResourceAction = AzapiFunctions.getResourceAction(GetResourceActionArgs.builder()
     *             .type(&#34;Microsoft.Automation/automationAccounts@2021-06-22&#34;)
     *             .resourceId(exampleAccount.id())
     *             .action(&#34;listKeys&#34;)
     *             .responseExportValues(&#34;*&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * 
     */
    public static Output<GetResourceActionResult> getResourceAction(GetResourceActionArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("azapi:index/getResourceAction:getResourceAction", TypeShape.of(GetResourceActionResult.class), args, Utilities.withVersion(options));
    }
    /**
     * This resource can perform resource action which gets information from an existing resource.
     * It&#39;s recommended to use `azapi.ResourceAction` data source to perform readonly action, please use `azapi.ResourceAction` resource,
     * if user wants to perform actions which change a resource&#39;s state.
     * 
     * ## Example Usage
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import com.pulumi.azure.core.ResourceGroup;
     * import com.pulumi.azure.core.ResourceGroupArgs;
     * import com.pulumi.azure.automation.Account;
     * import com.pulumi.azure.automation.AccountArgs;
     * import com.pulumi.azapi.AzapiFunctions;
     * import com.pulumi.azapi.inputs.GetResourceActionArgs;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *         var exampleResourceGroup = new ResourceGroup(&#34;exampleResourceGroup&#34;, ResourceGroupArgs.builder()        
     *             .location(&#34;west europe&#34;)
     *             .build());
     * 
     *         var exampleAccount = new Account(&#34;exampleAccount&#34;, AccountArgs.builder()        
     *             .resourceGroupName(exampleResourceGroup.name())
     *             .location(exampleResourceGroup.location())
     *             .skuName(&#34;Basic&#34;)
     *             .build());
     * 
     *         final var exampleResourceAction = AzapiFunctions.getResourceAction(GetResourceActionArgs.builder()
     *             .type(&#34;Microsoft.Automation/automationAccounts@2021-06-22&#34;)
     *             .resourceId(exampleAccount.id())
     *             .action(&#34;listKeys&#34;)
     *             .responseExportValues(&#34;*&#34;)
     *             .build());
     * 
     *     }
     * }
     * ```
     * 
     */
    public static CompletableFuture<GetResourceActionResult> getResourceActionPlain(GetResourceActionPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("azapi:index/getResourceAction:getResourceAction", TypeShape.of(GetResourceActionResult.class), args, Utilities.withVersion(options));
    }
}
