// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.azapi;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.dirien.azapi.ResourceArgs;
import io.dirien.azapi.Utilities;
import io.dirien.azapi.inputs.ResourceState;
import io.dirien.azapi.outputs.ResourceIdentity;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * This resource can manage any Azure resource manager resource.
 * 
 * ## Import
 * 
 * Azure resource can be imported using the `resource id`, e.g.
 * 
 * ```sh
 *  $ pulumi import azapi:index/resource:Resource example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resGroup1/providers/Microsoft.MachineLearningServices/workspaces/workspace1/computes/cluster1
 * ```
 * 
 *  It also supports specifying API version by using the `resource id` with `api-version` as a query parameter, e.g.
 * 
 * ```sh
 *  $ pulumi import azapi:index/resource:Resource example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resGroup1/providers/Microsoft.MachineLearningServices/workspaces/workspace1/computes/cluster1?api-version=2021-07-01
 * ```
 * 
 */
@ResourceType(type="azapi:index/resource:Resource")
public class Resource extends com.pulumi.resources.CustomResource {
    /**
     * A JSON object that contains the request body used to create and update azure resource.
     * 
     */
    @Export(name="body", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> body;

    /**
     * @return A JSON object that contains the request body used to create and update azure resource.
     * 
     */
    public Output<Optional<String>> body() {
        return Codegen.optional(this.body);
    }
    /**
     * A `identity` block as defined below.
     * 
     */
    @Export(name="identity", refs={ResourceIdentity.class}, tree="[0]")
    private Output<ResourceIdentity> identity;

    /**
     * @return A `identity` block as defined below.
     * 
     */
    public Output<ResourceIdentity> identity() {
        return this.identity;
    }
    /**
     * Whether ignore incorrect casing returned in `body` to suppress plan-diff. Defaults to `false`.
     * 
     */
    @Export(name="ignoreCasing", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> ignoreCasing;

    /**
     * @return Whether ignore incorrect casing returned in `body` to suppress plan-diff. Defaults to `false`.
     * 
     */
    public Output<Optional<Boolean>> ignoreCasing() {
        return Codegen.optional(this.ignoreCasing);
    }
    /**
     * Whether ignore not returned properties like credentials in `body` to suppress plan-diff. Defaults to `true`.
     * 
     */
    @Export(name="ignoreMissingProperty", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> ignoreMissingProperty;

    /**
     * @return Whether ignore not returned properties like credentials in `body` to suppress plan-diff. Defaults to `true`.
     * 
     */
    public Output<Optional<Boolean>> ignoreMissingProperty() {
        return Codegen.optional(this.ignoreMissingProperty);
    }
    /**
     * The Azure Region where the azure resource should exist.
     * 
     */
    @Export(name="location", refs={String.class}, tree="[0]")
    private Output<String> location;

    /**
     * @return The Azure Region where the azure resource should exist.
     * 
     */
    public Output<String> location() {
        return this.location;
    }
    /**
     * A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
     * 
     */
    @Export(name="locks", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> locks;

    /**
     * @return A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
     * 
     */
    public Output<Optional<List<String>>> locks() {
        return Codegen.optional(this.locks);
    }
    /**
     * Specifies the name of the azure resource. Changing this forces a new resource to be created.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Specifies the name of the azure resource. Changing this forces a new resource to be created.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The output json containing the properties specified in `response_export_values`. Here&#39;re some examples to decode json and extract the value.
     * 
     */
    @Export(name="output", refs={String.class}, tree="[0]")
    private Output<String> output;

    /**
     * @return The output json containing the properties specified in `response_export_values`. Here&#39;re some examples to decode json and extract the value.
     * 
     */
    public Output<String> output() {
        return this.output;
    }
    @Export(name="parentId", refs={String.class}, tree="[0]")
    private Output<String> parentId;

    public Output<String> parentId() {
        return this.parentId;
    }
    /**
     * A list of path that needs to be exported from response body.
     * Setting it to `[&#34;*&#34;]` will export the full response body.
     * Here&#39;s an example. If it sets to `[&#34;properties.loginServer&#34;, &#34;properties.policies.quarantinePolicy.status&#34;]`, it will set the following json to computed property `output`.
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *     }
     * }
     * ```
     * 
     */
    @Export(name="responseExportValues", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> responseExportValues;

    /**
     * @return A list of path that needs to be exported from response body.
     * Setting it to `[&#34;*&#34;]` will export the full response body.
     * Here&#39;s an example. If it sets to `[&#34;properties.loginServer&#34;, &#34;properties.policies.quarantinePolicy.status&#34;]`, it will set the following json to computed property `output`.
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *     }
     * }
     * ```
     * 
     */
    public Output<Optional<List<String>>> responseExportValues() {
        return Codegen.optional(this.responseExportValues);
    }
    /**
     * Whether enabled the validation on `type` and `body` with embedded schema. Defaults to `true`.
     * 
     */
    @Export(name="schemaValidationEnabled", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> schemaValidationEnabled;

    /**
     * @return Whether enabled the validation on `type` and `body` with embedded schema. Defaults to `true`.
     * 
     */
    public Output<Optional<Boolean>> schemaValidationEnabled() {
        return Codegen.optional(this.schemaValidationEnabled);
    }
    /**
     * A mapping of tags which should be assigned to the azure resource.
     * 
     */
    @Export(name="tags", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output<Map<String,String>> tags;

    /**
     * @return A mapping of tags which should be assigned to the azure resource.
     * 
     */
    public Output<Map<String,String>> tags() {
        return this.tags;
    }
    /**
     * It is in a format like `&lt;resource-type&gt;@&lt;api-version&gt;`. `&lt;resource-type&gt;` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
     * `&lt;api-version&gt;` is version of the API used to manage this azure resource.
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    /**
     * @return It is in a format like `&lt;resource-type&gt;@&lt;api-version&gt;`. `&lt;resource-type&gt;` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
     * `&lt;api-version&gt;` is version of the API used to manage this azure resource.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Resource(String name) {
        this(name, ResourceArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Resource(String name, ResourceArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Resource(String name, ResourceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("azapi:index/resource:Resource", name, args == null ? ResourceArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Resource(String name, Output<String> id, @Nullable ResourceState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("azapi:index/resource:Resource", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Resource get(String name, Output<String> id, @Nullable ResourceState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Resource(name, id, state, options);
    }
}
