// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package azapi

import (
	"context"
	"reflect"

	"github.com/dirien/pulumi-azapi/sdk/go/azapi/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/dirien/pulumi-azapi/sdk/go/azapi"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			current, err := azapi.GetClientConfig(ctx, &azapi.GetClientConfigArgs{}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("subscriptionId", current.SubscriptionId)
//			ctx.Export("tenantId", current.TenantId)
//			return nil
//		})
//	}
//
// ```
func GetClientConfig(ctx *pulumi.Context, args *GetClientConfigArgs, opts ...pulumi.InvokeOption) (*GetClientConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetClientConfigResult
	err := ctx.Invoke("azapi:index/getClientConfig:getClientConfig", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getClientConfig.
type GetClientConfigArgs struct {
	Timeouts *GetClientConfigTimeouts `pulumi:"timeouts"`
}

// A collection of values returned by getClientConfig.
type GetClientConfigResult struct {
	// The ID of this resource.
	Id string `pulumi:"id"`
	// The object ID of the identity. E.g. `00000000-0000-0000-0000-000000000000`
	ObjectId string `pulumi:"objectId"`
	// The subscription ID. E.g. `00000000-0000-0000-0000-000000000000`
	SubscriptionId string `pulumi:"subscriptionId"`
	// The resource ID of the subscription. E.g. `/subscriptions/00000000-0000-0000-0000-000000000000`
	SubscriptionResourceId string `pulumi:"subscriptionResourceId"`
	// The tenant ID. E.g. `00000000-0000-0000-0000-000000000000`
	TenantId string                   `pulumi:"tenantId"`
	Timeouts *GetClientConfigTimeouts `pulumi:"timeouts"`
}

func GetClientConfigOutput(ctx *pulumi.Context, args GetClientConfigOutputArgs, opts ...pulumi.InvokeOption) GetClientConfigResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetClientConfigResultOutput, error) {
			args := v.(GetClientConfigArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("azapi:index/getClientConfig:getClientConfig", args, GetClientConfigResultOutput{}, options).(GetClientConfigResultOutput), nil
		}).(GetClientConfigResultOutput)
}

// A collection of arguments for invoking getClientConfig.
type GetClientConfigOutputArgs struct {
	Timeouts GetClientConfigTimeoutsPtrInput `pulumi:"timeouts"`
}

func (GetClientConfigOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClientConfigArgs)(nil)).Elem()
}

// A collection of values returned by getClientConfig.
type GetClientConfigResultOutput struct{ *pulumi.OutputState }

func (GetClientConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClientConfigResult)(nil)).Elem()
}

func (o GetClientConfigResultOutput) ToGetClientConfigResultOutput() GetClientConfigResultOutput {
	return o
}

func (o GetClientConfigResultOutput) ToGetClientConfigResultOutputWithContext(ctx context.Context) GetClientConfigResultOutput {
	return o
}

// The ID of this resource.
func (o GetClientConfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetClientConfigResult) string { return v.Id }).(pulumi.StringOutput)
}

// The object ID of the identity. E.g. `00000000-0000-0000-0000-000000000000`
func (o GetClientConfigResultOutput) ObjectId() pulumi.StringOutput {
	return o.ApplyT(func(v GetClientConfigResult) string { return v.ObjectId }).(pulumi.StringOutput)
}

// The subscription ID. E.g. `00000000-0000-0000-0000-000000000000`
func (o GetClientConfigResultOutput) SubscriptionId() pulumi.StringOutput {
	return o.ApplyT(func(v GetClientConfigResult) string { return v.SubscriptionId }).(pulumi.StringOutput)
}

// The resource ID of the subscription. E.g. `/subscriptions/00000000-0000-0000-0000-000000000000`
func (o GetClientConfigResultOutput) SubscriptionResourceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetClientConfigResult) string { return v.SubscriptionResourceId }).(pulumi.StringOutput)
}

// The tenant ID. E.g. `00000000-0000-0000-0000-000000000000`
func (o GetClientConfigResultOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v GetClientConfigResult) string { return v.TenantId }).(pulumi.StringOutput)
}

func (o GetClientConfigResultOutput) Timeouts() GetClientConfigTimeoutsPtrOutput {
	return o.ApplyT(func(v GetClientConfigResult) *GetClientConfigTimeouts { return v.Timeouts }).(GetClientConfigTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetClientConfigResultOutput{})
}
