// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package azapi

import (
	"context"
	"reflect"

	"github.com/dirien/pulumi-azapi/sdk/go/azapi/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/dirien/pulumi-azapi/sdk/go/azapi"
//	"github.com/pulumi/pulumi-azure/sdk/v6/go/azure/automation"
//	"github.com/pulumi/pulumi-azure/sdk/v6/go/azure/core"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			exampleResourceGroup, err := core.NewResourceGroup(ctx, "exampleResourceGroup", &core.ResourceGroupArgs{
//				Location: pulumi.String("west europe"),
//			})
//			if err != nil {
//				return err
//			}
//			exampleAccount, err := automation.NewAccount(ctx, "exampleAccount", &automation.AccountArgs{
//				ResourceGroupName: exampleResourceGroup.Name,
//				Location:          exampleResourceGroup.Location,
//				SkuName:           pulumi.String("Basic"),
//			})
//			if err != nil {
//				return err
//			}
//			_ = azapi.LookupResourceActionOutput(ctx, azapi.GetResourceActionOutputArgs{
//				Type:       pulumi.String("Microsoft.Automation/automationAccounts@2021-06-22"),
//				ResourceId: exampleAccount.ID(),
//				Action:     pulumi.String("listKeys"),
//				ResponseExportValues: pulumi.Any{
//					"*",
//				},
//			}, nil)
//			return nil
//		})
//	}
//
// ```
func LookupResourceAction(ctx *pulumi.Context, args *LookupResourceActionArgs, opts ...pulumi.InvokeOption) (*LookupResourceActionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupResourceActionResult
	err := ctx.Invoke("azapi:index/getResourceAction:getResourceAction", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getResourceAction.
type LookupResourceActionArgs struct {
	Action                        *string                    `pulumi:"action"`
	Body                          interface{}                `pulumi:"body"`
	Headers                       map[string]string          `pulumi:"headers"`
	Method                        *string                    `pulumi:"method"`
	QueryParameters               map[string][]string        `pulumi:"queryParameters"`
	ResourceId                    *string                    `pulumi:"resourceId"`
	ResponseExportValues          interface{}                `pulumi:"responseExportValues"`
	Retry                         *GetResourceActionRetry    `pulumi:"retry"`
	SensitiveResponseExportValues interface{}                `pulumi:"sensitiveResponseExportValues"`
	Timeouts                      *GetResourceActionTimeouts `pulumi:"timeouts"`
	Type                          string                     `pulumi:"type"`
}

// A collection of values returned by getResourceAction.
type LookupResourceActionResult struct {
	Action                        *string                    `pulumi:"action"`
	Body                          interface{}                `pulumi:"body"`
	Headers                       map[string]string          `pulumi:"headers"`
	Id                            string                     `pulumi:"id"`
	Method                        string                     `pulumi:"method"`
	Output                        interface{}                `pulumi:"output"`
	QueryParameters               map[string][]string        `pulumi:"queryParameters"`
	ResourceId                    *string                    `pulumi:"resourceId"`
	ResponseExportValues          interface{}                `pulumi:"responseExportValues"`
	Retry                         *GetResourceActionRetry    `pulumi:"retry"`
	SensitiveOutput               interface{}                `pulumi:"sensitiveOutput"`
	SensitiveResponseExportValues interface{}                `pulumi:"sensitiveResponseExportValues"`
	Timeouts                      *GetResourceActionTimeouts `pulumi:"timeouts"`
	Type                          string                     `pulumi:"type"`
}

func LookupResourceActionOutput(ctx *pulumi.Context, args LookupResourceActionOutputArgs, opts ...pulumi.InvokeOption) LookupResourceActionResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupResourceActionResultOutput, error) {
			args := v.(LookupResourceActionArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("azapi:index/getResourceAction:getResourceAction", args, LookupResourceActionResultOutput{}, options).(LookupResourceActionResultOutput), nil
		}).(LookupResourceActionResultOutput)
}

// A collection of arguments for invoking getResourceAction.
type LookupResourceActionOutputArgs struct {
	Action                        pulumi.StringPtrInput             `pulumi:"action"`
	Body                          pulumi.Input                      `pulumi:"body"`
	Headers                       pulumi.StringMapInput             `pulumi:"headers"`
	Method                        pulumi.StringPtrInput             `pulumi:"method"`
	QueryParameters               pulumi.StringArrayMapInput        `pulumi:"queryParameters"`
	ResourceId                    pulumi.StringPtrInput             `pulumi:"resourceId"`
	ResponseExportValues          pulumi.Input                      `pulumi:"responseExportValues"`
	Retry                         GetResourceActionRetryPtrInput    `pulumi:"retry"`
	SensitiveResponseExportValues pulumi.Input                      `pulumi:"sensitiveResponseExportValues"`
	Timeouts                      GetResourceActionTimeoutsPtrInput `pulumi:"timeouts"`
	Type                          pulumi.StringInput                `pulumi:"type"`
}

func (LookupResourceActionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupResourceActionArgs)(nil)).Elem()
}

// A collection of values returned by getResourceAction.
type LookupResourceActionResultOutput struct{ *pulumi.OutputState }

func (LookupResourceActionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupResourceActionResult)(nil)).Elem()
}

func (o LookupResourceActionResultOutput) ToLookupResourceActionResultOutput() LookupResourceActionResultOutput {
	return o
}

func (o LookupResourceActionResultOutput) ToLookupResourceActionResultOutputWithContext(ctx context.Context) LookupResourceActionResultOutput {
	return o
}

func (o LookupResourceActionResultOutput) Action() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupResourceActionResult) *string { return v.Action }).(pulumi.StringPtrOutput)
}

func (o LookupResourceActionResultOutput) Body() pulumi.AnyOutput {
	return o.ApplyT(func(v LookupResourceActionResult) interface{} { return v.Body }).(pulumi.AnyOutput)
}

func (o LookupResourceActionResultOutput) Headers() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupResourceActionResult) map[string]string { return v.Headers }).(pulumi.StringMapOutput)
}

func (o LookupResourceActionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupResourceActionResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupResourceActionResultOutput) Method() pulumi.StringOutput {
	return o.ApplyT(func(v LookupResourceActionResult) string { return v.Method }).(pulumi.StringOutput)
}

func (o LookupResourceActionResultOutput) Output() pulumi.AnyOutput {
	return o.ApplyT(func(v LookupResourceActionResult) interface{} { return v.Output }).(pulumi.AnyOutput)
}

func (o LookupResourceActionResultOutput) QueryParameters() pulumi.StringArrayMapOutput {
	return o.ApplyT(func(v LookupResourceActionResult) map[string][]string { return v.QueryParameters }).(pulumi.StringArrayMapOutput)
}

func (o LookupResourceActionResultOutput) ResourceId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupResourceActionResult) *string { return v.ResourceId }).(pulumi.StringPtrOutput)
}

func (o LookupResourceActionResultOutput) ResponseExportValues() pulumi.AnyOutput {
	return o.ApplyT(func(v LookupResourceActionResult) interface{} { return v.ResponseExportValues }).(pulumi.AnyOutput)
}

func (o LookupResourceActionResultOutput) Retry() GetResourceActionRetryPtrOutput {
	return o.ApplyT(func(v LookupResourceActionResult) *GetResourceActionRetry { return v.Retry }).(GetResourceActionRetryPtrOutput)
}

func (o LookupResourceActionResultOutput) SensitiveOutput() pulumi.AnyOutput {
	return o.ApplyT(func(v LookupResourceActionResult) interface{} { return v.SensitiveOutput }).(pulumi.AnyOutput)
}

func (o LookupResourceActionResultOutput) SensitiveResponseExportValues() pulumi.AnyOutput {
	return o.ApplyT(func(v LookupResourceActionResult) interface{} { return v.SensitiveResponseExportValues }).(pulumi.AnyOutput)
}

func (o LookupResourceActionResultOutput) Timeouts() GetResourceActionTimeoutsPtrOutput {
	return o.ApplyT(func(v LookupResourceActionResult) *GetResourceActionTimeouts { return v.Timeouts }).(GetResourceActionTimeoutsPtrOutput)
}

func (o LookupResourceActionResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupResourceActionResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupResourceActionResultOutput{})
}
