// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package azapi

import (
	"context"
	"reflect"

	"errors"
	"github.com/dirien/pulumi-azapi/sdk/go/azapi/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This resource can manage a subset of any existing Azure resource manager resource's properties.
//
// > **Note** This resource is used to add or modify properties on an existing resource.
// When delete `UpdateResource`, no operation will be performed, and these properties will stay unchanged.
// If you want to restore the modified properties to some values, you must apply the restored properties before deleting.
//
// ## Example Usage
type UpdateResource struct {
	pulumi.CustomResourceState

	// A dynamic attribute that contains the request body used to add on an existing azure resource.
	Body pulumi.AnyOutput `pulumi:"body"`
	// Deprecated: This feature is deprecated and will be removed in a major release. Please use the `lifecycle.ignore_changes` argument to specify the fields in `body` to ignore.
	IgnoreBodyChanges pulumi.StringArrayOutput `pulumi:"ignoreBodyChanges"`
	// Whether ignore incorrect casing returned in `body` to suppress plan-diff. Defaults to `false`.
	IgnoreCasing pulumi.BoolOutput `pulumi:"ignoreCasing"`
	// Whether ignore not returned properties like credentials in `body` to suppress plan-diff. Defaults to `true`.
	// It's recommend to enable this option when some sensitive properties are not returned in response body, instead of setting them in `lifecycle.ignore_changes` because it will make the sensitive fields unable to update.
	IgnoreMissingProperty pulumi.BoolOutput `pulumi:"ignoreMissingProperty"`
	// A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
	Locks pulumi.StringArrayOutput `pulumi:"locks"`
	// Specifies the name of the azure resource. Changing this forces a new resource to be created.
	Name pulumi.StringOutput `pulumi:"name"`
	// The HCL object containing the properties specified in `responseExportValues`. Here are some examples to use the values.
	Output pulumi.AnyOutput `pulumi:"output"`
	// The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created. It supports different kinds of deployment scope for **top level** resources:
	// - resource group scope: `parentId` should be the ID of a resource group, it's recommended to manage a resource group by azurerm_resource_group.
	// - management group scope: `parentId` should be the ID of a management group, it's recommended to manage a management group by azurerm_management_group.
	// - extension scope: `parentId` should be the ID of the resource you're adding the extension to.
	// - subscription scope: `parentId` should be like `/subscriptions/00000000-0000-0000-0000-000000000000`
	// - tenant scope: `parentId` should be `/`
	//
	// For child level resources, the `parentId` should be the ID of its parent resource, for example, subnet resource's `parentId` is the ID of the vnet.
	ParentId pulumi.StringOutput `pulumi:"parentId"`
	// The ID of an existing azure source. Changing this forces a new azure resource to be created.
	//
	// > **Note:** Configuring `name` and `parentId` is an alternative way to configure `resourceId`.
	ResourceId pulumi.StringOutput `pulumi:"resourceId"`
	// A list of path that needs to be exported from response body.
	// Setting it to `["*"]` will export the full response body.
	// Here's an example. If it sets to `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to computed property `output`.
	ResponseExportValues pulumi.StringArrayOutput        `pulumi:"responseExportValues"`
	Timeouts             UpdateResourceTimeoutsPtrOutput `pulumi:"timeouts"`
	// It is in a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
	// `<api-version>` is version of the API used to manage this azure resource.
	Type pulumi.StringOutput `pulumi:"type"`
}

// NewUpdateResource registers a new resource with the given unique name, arguments, and options.
func NewUpdateResource(ctx *pulumi.Context,
	name string, args *UpdateResourceArgs, opts ...pulumi.ResourceOption) (*UpdateResource, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource UpdateResource
	err := ctx.RegisterResource("azapi:index/updateResource:UpdateResource", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUpdateResource gets an existing UpdateResource resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUpdateResource(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UpdateResourceState, opts ...pulumi.ResourceOption) (*UpdateResource, error) {
	var resource UpdateResource
	err := ctx.ReadResource("azapi:index/updateResource:UpdateResource", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering UpdateResource resources.
type updateResourceState struct {
	// A dynamic attribute that contains the request body used to add on an existing azure resource.
	Body interface{} `pulumi:"body"`
	// Deprecated: This feature is deprecated and will be removed in a major release. Please use the `lifecycle.ignore_changes` argument to specify the fields in `body` to ignore.
	IgnoreBodyChanges []string `pulumi:"ignoreBodyChanges"`
	// Whether ignore incorrect casing returned in `body` to suppress plan-diff. Defaults to `false`.
	IgnoreCasing *bool `pulumi:"ignoreCasing"`
	// Whether ignore not returned properties like credentials in `body` to suppress plan-diff. Defaults to `true`.
	// It's recommend to enable this option when some sensitive properties are not returned in response body, instead of setting them in `lifecycle.ignore_changes` because it will make the sensitive fields unable to update.
	IgnoreMissingProperty *bool `pulumi:"ignoreMissingProperty"`
	// A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
	Locks []string `pulumi:"locks"`
	// Specifies the name of the azure resource. Changing this forces a new resource to be created.
	Name *string `pulumi:"name"`
	// The HCL object containing the properties specified in `responseExportValues`. Here are some examples to use the values.
	Output interface{} `pulumi:"output"`
	// The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created. It supports different kinds of deployment scope for **top level** resources:
	// - resource group scope: `parentId` should be the ID of a resource group, it's recommended to manage a resource group by azurerm_resource_group.
	// - management group scope: `parentId` should be the ID of a management group, it's recommended to manage a management group by azurerm_management_group.
	// - extension scope: `parentId` should be the ID of the resource you're adding the extension to.
	// - subscription scope: `parentId` should be like `/subscriptions/00000000-0000-0000-0000-000000000000`
	// - tenant scope: `parentId` should be `/`
	//
	// For child level resources, the `parentId` should be the ID of its parent resource, for example, subnet resource's `parentId` is the ID of the vnet.
	ParentId *string `pulumi:"parentId"`
	// The ID of an existing azure source. Changing this forces a new azure resource to be created.
	//
	// > **Note:** Configuring `name` and `parentId` is an alternative way to configure `resourceId`.
	ResourceId *string `pulumi:"resourceId"`
	// A list of path that needs to be exported from response body.
	// Setting it to `["*"]` will export the full response body.
	// Here's an example. If it sets to `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to computed property `output`.
	ResponseExportValues []string                `pulumi:"responseExportValues"`
	Timeouts             *UpdateResourceTimeouts `pulumi:"timeouts"`
	// It is in a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
	// `<api-version>` is version of the API used to manage this azure resource.
	Type *string `pulumi:"type"`
}

type UpdateResourceState struct {
	// A dynamic attribute that contains the request body used to add on an existing azure resource.
	Body pulumi.Input
	// Deprecated: This feature is deprecated and will be removed in a major release. Please use the `lifecycle.ignore_changes` argument to specify the fields in `body` to ignore.
	IgnoreBodyChanges pulumi.StringArrayInput
	// Whether ignore incorrect casing returned in `body` to suppress plan-diff. Defaults to `false`.
	IgnoreCasing pulumi.BoolPtrInput
	// Whether ignore not returned properties like credentials in `body` to suppress plan-diff. Defaults to `true`.
	// It's recommend to enable this option when some sensitive properties are not returned in response body, instead of setting them in `lifecycle.ignore_changes` because it will make the sensitive fields unable to update.
	IgnoreMissingProperty pulumi.BoolPtrInput
	// A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
	Locks pulumi.StringArrayInput
	// Specifies the name of the azure resource. Changing this forces a new resource to be created.
	Name pulumi.StringPtrInput
	// The HCL object containing the properties specified in `responseExportValues`. Here are some examples to use the values.
	Output pulumi.Input
	// The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created. It supports different kinds of deployment scope for **top level** resources:
	// - resource group scope: `parentId` should be the ID of a resource group, it's recommended to manage a resource group by azurerm_resource_group.
	// - management group scope: `parentId` should be the ID of a management group, it's recommended to manage a management group by azurerm_management_group.
	// - extension scope: `parentId` should be the ID of the resource you're adding the extension to.
	// - subscription scope: `parentId` should be like `/subscriptions/00000000-0000-0000-0000-000000000000`
	// - tenant scope: `parentId` should be `/`
	//
	// For child level resources, the `parentId` should be the ID of its parent resource, for example, subnet resource's `parentId` is the ID of the vnet.
	ParentId pulumi.StringPtrInput
	// The ID of an existing azure source. Changing this forces a new azure resource to be created.
	//
	// > **Note:** Configuring `name` and `parentId` is an alternative way to configure `resourceId`.
	ResourceId pulumi.StringPtrInput
	// A list of path that needs to be exported from response body.
	// Setting it to `["*"]` will export the full response body.
	// Here's an example. If it sets to `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to computed property `output`.
	ResponseExportValues pulumi.StringArrayInput
	Timeouts             UpdateResourceTimeoutsPtrInput
	// It is in a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
	// `<api-version>` is version of the API used to manage this azure resource.
	Type pulumi.StringPtrInput
}

func (UpdateResourceState) ElementType() reflect.Type {
	return reflect.TypeOf((*updateResourceState)(nil)).Elem()
}

type updateResourceArgs struct {
	// A dynamic attribute that contains the request body used to add on an existing azure resource.
	Body interface{} `pulumi:"body"`
	// Deprecated: This feature is deprecated and will be removed in a major release. Please use the `lifecycle.ignore_changes` argument to specify the fields in `body` to ignore.
	IgnoreBodyChanges []string `pulumi:"ignoreBodyChanges"`
	// Whether ignore incorrect casing returned in `body` to suppress plan-diff. Defaults to `false`.
	IgnoreCasing *bool `pulumi:"ignoreCasing"`
	// Whether ignore not returned properties like credentials in `body` to suppress plan-diff. Defaults to `true`.
	// It's recommend to enable this option when some sensitive properties are not returned in response body, instead of setting them in `lifecycle.ignore_changes` because it will make the sensitive fields unable to update.
	IgnoreMissingProperty *bool `pulumi:"ignoreMissingProperty"`
	// A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
	Locks []string `pulumi:"locks"`
	// Specifies the name of the azure resource. Changing this forces a new resource to be created.
	Name *string `pulumi:"name"`
	// The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created. It supports different kinds of deployment scope for **top level** resources:
	// - resource group scope: `parentId` should be the ID of a resource group, it's recommended to manage a resource group by azurerm_resource_group.
	// - management group scope: `parentId` should be the ID of a management group, it's recommended to manage a management group by azurerm_management_group.
	// - extension scope: `parentId` should be the ID of the resource you're adding the extension to.
	// - subscription scope: `parentId` should be like `/subscriptions/00000000-0000-0000-0000-000000000000`
	// - tenant scope: `parentId` should be `/`
	//
	// For child level resources, the `parentId` should be the ID of its parent resource, for example, subnet resource's `parentId` is the ID of the vnet.
	ParentId *string `pulumi:"parentId"`
	// The ID of an existing azure source. Changing this forces a new azure resource to be created.
	//
	// > **Note:** Configuring `name` and `parentId` is an alternative way to configure `resourceId`.
	ResourceId *string `pulumi:"resourceId"`
	// A list of path that needs to be exported from response body.
	// Setting it to `["*"]` will export the full response body.
	// Here's an example. If it sets to `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to computed property `output`.
	ResponseExportValues []string                `pulumi:"responseExportValues"`
	Timeouts             *UpdateResourceTimeouts `pulumi:"timeouts"`
	// It is in a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
	// `<api-version>` is version of the API used to manage this azure resource.
	Type string `pulumi:"type"`
}

// The set of arguments for constructing a UpdateResource resource.
type UpdateResourceArgs struct {
	// A dynamic attribute that contains the request body used to add on an existing azure resource.
	Body pulumi.Input
	// Deprecated: This feature is deprecated and will be removed in a major release. Please use the `lifecycle.ignore_changes` argument to specify the fields in `body` to ignore.
	IgnoreBodyChanges pulumi.StringArrayInput
	// Whether ignore incorrect casing returned in `body` to suppress plan-diff. Defaults to `false`.
	IgnoreCasing pulumi.BoolPtrInput
	// Whether ignore not returned properties like credentials in `body` to suppress plan-diff. Defaults to `true`.
	// It's recommend to enable this option when some sensitive properties are not returned in response body, instead of setting them in `lifecycle.ignore_changes` because it will make the sensitive fields unable to update.
	IgnoreMissingProperty pulumi.BoolPtrInput
	// A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
	Locks pulumi.StringArrayInput
	// Specifies the name of the azure resource. Changing this forces a new resource to be created.
	Name pulumi.StringPtrInput
	// The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created. It supports different kinds of deployment scope for **top level** resources:
	// - resource group scope: `parentId` should be the ID of a resource group, it's recommended to manage a resource group by azurerm_resource_group.
	// - management group scope: `parentId` should be the ID of a management group, it's recommended to manage a management group by azurerm_management_group.
	// - extension scope: `parentId` should be the ID of the resource you're adding the extension to.
	// - subscription scope: `parentId` should be like `/subscriptions/00000000-0000-0000-0000-000000000000`
	// - tenant scope: `parentId` should be `/`
	//
	// For child level resources, the `parentId` should be the ID of its parent resource, for example, subnet resource's `parentId` is the ID of the vnet.
	ParentId pulumi.StringPtrInput
	// The ID of an existing azure source. Changing this forces a new azure resource to be created.
	//
	// > **Note:** Configuring `name` and `parentId` is an alternative way to configure `resourceId`.
	ResourceId pulumi.StringPtrInput
	// A list of path that needs to be exported from response body.
	// Setting it to `["*"]` will export the full response body.
	// Here's an example. If it sets to `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to computed property `output`.
	ResponseExportValues pulumi.StringArrayInput
	Timeouts             UpdateResourceTimeoutsPtrInput
	// It is in a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
	// `<api-version>` is version of the API used to manage this azure resource.
	Type pulumi.StringInput
}

func (UpdateResourceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*updateResourceArgs)(nil)).Elem()
}

type UpdateResourceInput interface {
	pulumi.Input

	ToUpdateResourceOutput() UpdateResourceOutput
	ToUpdateResourceOutputWithContext(ctx context.Context) UpdateResourceOutput
}

func (*UpdateResource) ElementType() reflect.Type {
	return reflect.TypeOf((**UpdateResource)(nil)).Elem()
}

func (i *UpdateResource) ToUpdateResourceOutput() UpdateResourceOutput {
	return i.ToUpdateResourceOutputWithContext(context.Background())
}

func (i *UpdateResource) ToUpdateResourceOutputWithContext(ctx context.Context) UpdateResourceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UpdateResourceOutput)
}

// UpdateResourceArrayInput is an input type that accepts UpdateResourceArray and UpdateResourceArrayOutput values.
// You can construct a concrete instance of `UpdateResourceArrayInput` via:
//
//	UpdateResourceArray{ UpdateResourceArgs{...} }
type UpdateResourceArrayInput interface {
	pulumi.Input

	ToUpdateResourceArrayOutput() UpdateResourceArrayOutput
	ToUpdateResourceArrayOutputWithContext(context.Context) UpdateResourceArrayOutput
}

type UpdateResourceArray []UpdateResourceInput

func (UpdateResourceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*UpdateResource)(nil)).Elem()
}

func (i UpdateResourceArray) ToUpdateResourceArrayOutput() UpdateResourceArrayOutput {
	return i.ToUpdateResourceArrayOutputWithContext(context.Background())
}

func (i UpdateResourceArray) ToUpdateResourceArrayOutputWithContext(ctx context.Context) UpdateResourceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UpdateResourceArrayOutput)
}

// UpdateResourceMapInput is an input type that accepts UpdateResourceMap and UpdateResourceMapOutput values.
// You can construct a concrete instance of `UpdateResourceMapInput` via:
//
//	UpdateResourceMap{ "key": UpdateResourceArgs{...} }
type UpdateResourceMapInput interface {
	pulumi.Input

	ToUpdateResourceMapOutput() UpdateResourceMapOutput
	ToUpdateResourceMapOutputWithContext(context.Context) UpdateResourceMapOutput
}

type UpdateResourceMap map[string]UpdateResourceInput

func (UpdateResourceMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*UpdateResource)(nil)).Elem()
}

func (i UpdateResourceMap) ToUpdateResourceMapOutput() UpdateResourceMapOutput {
	return i.ToUpdateResourceMapOutputWithContext(context.Background())
}

func (i UpdateResourceMap) ToUpdateResourceMapOutputWithContext(ctx context.Context) UpdateResourceMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UpdateResourceMapOutput)
}

type UpdateResourceOutput struct{ *pulumi.OutputState }

func (UpdateResourceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**UpdateResource)(nil)).Elem()
}

func (o UpdateResourceOutput) ToUpdateResourceOutput() UpdateResourceOutput {
	return o
}

func (o UpdateResourceOutput) ToUpdateResourceOutputWithContext(ctx context.Context) UpdateResourceOutput {
	return o
}

// A dynamic attribute that contains the request body used to add on an existing azure resource.
func (o UpdateResourceOutput) Body() pulumi.AnyOutput {
	return o.ApplyT(func(v *UpdateResource) pulumi.AnyOutput { return v.Body }).(pulumi.AnyOutput)
}

// Deprecated: This feature is deprecated and will be removed in a major release. Please use the `lifecycle.ignore_changes` argument to specify the fields in `body` to ignore.
func (o UpdateResourceOutput) IgnoreBodyChanges() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *UpdateResource) pulumi.StringArrayOutput { return v.IgnoreBodyChanges }).(pulumi.StringArrayOutput)
}

// Whether ignore incorrect casing returned in `body` to suppress plan-diff. Defaults to `false`.
func (o UpdateResourceOutput) IgnoreCasing() pulumi.BoolOutput {
	return o.ApplyT(func(v *UpdateResource) pulumi.BoolOutput { return v.IgnoreCasing }).(pulumi.BoolOutput)
}

// Whether ignore not returned properties like credentials in `body` to suppress plan-diff. Defaults to `true`.
// It's recommend to enable this option when some sensitive properties are not returned in response body, instead of setting them in `lifecycle.ignore_changes` because it will make the sensitive fields unable to update.
func (o UpdateResourceOutput) IgnoreMissingProperty() pulumi.BoolOutput {
	return o.ApplyT(func(v *UpdateResource) pulumi.BoolOutput { return v.IgnoreMissingProperty }).(pulumi.BoolOutput)
}

// A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
func (o UpdateResourceOutput) Locks() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *UpdateResource) pulumi.StringArrayOutput { return v.Locks }).(pulumi.StringArrayOutput)
}

// Specifies the name of the azure resource. Changing this forces a new resource to be created.
func (o UpdateResourceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *UpdateResource) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The HCL object containing the properties specified in `responseExportValues`. Here are some examples to use the values.
func (o UpdateResourceOutput) Output() pulumi.AnyOutput {
	return o.ApplyT(func(v *UpdateResource) pulumi.AnyOutput { return v.Output }).(pulumi.AnyOutput)
}

// The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created. It supports different kinds of deployment scope for **top level** resources:
// - resource group scope: `parentId` should be the ID of a resource group, it's recommended to manage a resource group by azurerm_resource_group.
// - management group scope: `parentId` should be the ID of a management group, it's recommended to manage a management group by azurerm_management_group.
// - extension scope: `parentId` should be the ID of the resource you're adding the extension to.
// - subscription scope: `parentId` should be like `/subscriptions/00000000-0000-0000-0000-000000000000`
// - tenant scope: `parentId` should be `/`
//
// For child level resources, the `parentId` should be the ID of its parent resource, for example, subnet resource's `parentId` is the ID of the vnet.
func (o UpdateResourceOutput) ParentId() pulumi.StringOutput {
	return o.ApplyT(func(v *UpdateResource) pulumi.StringOutput { return v.ParentId }).(pulumi.StringOutput)
}

// The ID of an existing azure source. Changing this forces a new azure resource to be created.
//
// > **Note:** Configuring `name` and `parentId` is an alternative way to configure `resourceId`.
func (o UpdateResourceOutput) ResourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *UpdateResource) pulumi.StringOutput { return v.ResourceId }).(pulumi.StringOutput)
}

// A list of path that needs to be exported from response body.
// Setting it to `["*"]` will export the full response body.
// Here's an example. If it sets to `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to computed property `output`.
func (o UpdateResourceOutput) ResponseExportValues() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *UpdateResource) pulumi.StringArrayOutput { return v.ResponseExportValues }).(pulumi.StringArrayOutput)
}

func (o UpdateResourceOutput) Timeouts() UpdateResourceTimeoutsPtrOutput {
	return o.ApplyT(func(v *UpdateResource) UpdateResourceTimeoutsPtrOutput { return v.Timeouts }).(UpdateResourceTimeoutsPtrOutput)
}

// It is in a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
// `<api-version>` is version of the API used to manage this azure resource.
func (o UpdateResourceOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *UpdateResource) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

type UpdateResourceArrayOutput struct{ *pulumi.OutputState }

func (UpdateResourceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*UpdateResource)(nil)).Elem()
}

func (o UpdateResourceArrayOutput) ToUpdateResourceArrayOutput() UpdateResourceArrayOutput {
	return o
}

func (o UpdateResourceArrayOutput) ToUpdateResourceArrayOutputWithContext(ctx context.Context) UpdateResourceArrayOutput {
	return o
}

func (o UpdateResourceArrayOutput) Index(i pulumi.IntInput) UpdateResourceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *UpdateResource {
		return vs[0].([]*UpdateResource)[vs[1].(int)]
	}).(UpdateResourceOutput)
}

type UpdateResourceMapOutput struct{ *pulumi.OutputState }

func (UpdateResourceMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*UpdateResource)(nil)).Elem()
}

func (o UpdateResourceMapOutput) ToUpdateResourceMapOutput() UpdateResourceMapOutput {
	return o
}

func (o UpdateResourceMapOutput) ToUpdateResourceMapOutputWithContext(ctx context.Context) UpdateResourceMapOutput {
	return o
}

func (o UpdateResourceMapOutput) MapIndex(k pulumi.StringInput) UpdateResourceOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *UpdateResource {
		return vs[0].(map[string]*UpdateResource)[vs[1].(string)]
	}).(UpdateResourceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UpdateResourceInput)(nil)).Elem(), &UpdateResource{})
	pulumi.RegisterInputType(reflect.TypeOf((*UpdateResourceArrayInput)(nil)).Elem(), UpdateResourceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*UpdateResourceMapInput)(nil)).Elem(), UpdateResourceMap{})
	pulumi.RegisterOutputType(UpdateResourceOutput{})
	pulumi.RegisterOutputType(UpdateResourceArrayOutput{})
	pulumi.RegisterOutputType(UpdateResourceMapOutput{})
}
