// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.dirien.azapi.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ResourceActionState extends com.pulumi.resources.ResourceArgs {

    public static final ResourceActionState Empty = new ResourceActionState();

    /**
     * The name of the resource action. It&#39;s also possible to make Http requests towards the resource ID if leave this field empty.
     * 
     */
    @Import(name="action")
    private @Nullable Output<String> action;

    /**
     * @return The name of the resource action. It&#39;s also possible to make Http requests towards the resource ID if leave this field empty.
     * 
     */
    public Optional<Output<String>> action() {
        return Optional.ofNullable(this.action);
    }

    /**
     * A JSON object that contains the request body.
     * 
     */
    @Import(name="body")
    private @Nullable Output<String> body;

    /**
     * @return A JSON object that contains the request body.
     * 
     */
    public Optional<Output<String>> body() {
        return Optional.ofNullable(this.body);
    }

    /**
     * A list of ARM resource IDs which are used to avoid modify azapi resources at the same time.
     * 
     */
    @Import(name="locks")
    private @Nullable Output<List<String>> locks;

    /**
     * @return A list of ARM resource IDs which are used to avoid modify azapi resources at the same time.
     * 
     */
    public Optional<Output<List<String>>> locks() {
        return Optional.ofNullable(this.locks);
    }

    /**
     * Specifies the Http method of the azure resource action. Allowed values are `POST`, `PATCH`, `PUT` and `DELETE`. Defaults to `POST`.
     * 
     */
    @Import(name="method")
    private @Nullable Output<String> method;

    /**
     * @return Specifies the Http method of the azure resource action. Allowed values are `POST`, `PATCH`, `PUT` and `DELETE`. Defaults to `POST`.
     * 
     */
    public Optional<Output<String>> method() {
        return Optional.ofNullable(this.method);
    }

    /**
     * The output json containing the properties specified in `response_export_values`. Here are some examples to decode json and extract the value.
     * 
     */
    @Import(name="output")
    private @Nullable Output<String> output;

    /**
     * @return The output json containing the properties specified in `response_export_values`. Here are some examples to decode json and extract the value.
     * 
     */
    public Optional<Output<String>> output() {
        return Optional.ofNullable(this.output);
    }

    /**
     * The ID of an existing azure source.
     * 
     */
    @Import(name="resourceId")
    private @Nullable Output<String> resourceId;

    /**
     * @return The ID of an existing azure source.
     * 
     */
    public Optional<Output<String>> resourceId() {
        return Optional.ofNullable(this.resourceId);
    }

    /**
     * A list of path that needs to be exported from response body.
     * Setting it to `[&#34;*&#34;]` will export the full response body.
     * Here&#39;s an example. If it sets to `[&#34;keys&#34;]`, it will set the following json to computed property `output`.
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *     }
     * }
     * ```
     * 
     */
    @Import(name="responseExportValues")
    private @Nullable Output<List<String>> responseExportValues;

    /**
     * @return A list of path that needs to be exported from response body.
     * Setting it to `[&#34;*&#34;]` will export the full response body.
     * Here&#39;s an example. If it sets to `[&#34;keys&#34;]`, it will set the following json to computed property `output`.
     * ```java
     * package generated_program;
     * 
     * import com.pulumi.Context;
     * import com.pulumi.Pulumi;
     * import com.pulumi.core.Output;
     * import java.util.List;
     * import java.util.ArrayList;
     * import java.util.Map;
     * import java.io.File;
     * import java.nio.file.Files;
     * import java.nio.file.Paths;
     * 
     * public class App {
     *     public static void main(String[] args) {
     *         Pulumi.run(App::stack);
     *     }
     * 
     *     public static void stack(Context ctx) {
     *     }
     * }
     * ```
     * 
     */
    public Optional<Output<List<String>>> responseExportValues() {
        return Optional.ofNullable(this.responseExportValues);
    }

    /**
     * It is in a format like `&lt;resource-type&gt;@&lt;api-version&gt;`. `&lt;resource-type&gt;` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
     * `&lt;api-version&gt;` is version of the API used to manage this azure resource.
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return It is in a format like `&lt;resource-type&gt;@&lt;api-version&gt;`. `&lt;resource-type&gt;` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
     * `&lt;api-version&gt;` is version of the API used to manage this azure resource.
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private ResourceActionState() {}

    private ResourceActionState(ResourceActionState $) {
        this.action = $.action;
        this.body = $.body;
        this.locks = $.locks;
        this.method = $.method;
        this.output = $.output;
        this.resourceId = $.resourceId;
        this.responseExportValues = $.responseExportValues;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ResourceActionState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ResourceActionState $;

        public Builder() {
            $ = new ResourceActionState();
        }

        public Builder(ResourceActionState defaults) {
            $ = new ResourceActionState(Objects.requireNonNull(defaults));
        }

        /**
         * @param action The name of the resource action. It&#39;s also possible to make Http requests towards the resource ID if leave this field empty.
         * 
         * @return builder
         * 
         */
        public Builder action(@Nullable Output<String> action) {
            $.action = action;
            return this;
        }

        /**
         * @param action The name of the resource action. It&#39;s also possible to make Http requests towards the resource ID if leave this field empty.
         * 
         * @return builder
         * 
         */
        public Builder action(String action) {
            return action(Output.of(action));
        }

        /**
         * @param body A JSON object that contains the request body.
         * 
         * @return builder
         * 
         */
        public Builder body(@Nullable Output<String> body) {
            $.body = body;
            return this;
        }

        /**
         * @param body A JSON object that contains the request body.
         * 
         * @return builder
         * 
         */
        public Builder body(String body) {
            return body(Output.of(body));
        }

        /**
         * @param locks A list of ARM resource IDs which are used to avoid modify azapi resources at the same time.
         * 
         * @return builder
         * 
         */
        public Builder locks(@Nullable Output<List<String>> locks) {
            $.locks = locks;
            return this;
        }

        /**
         * @param locks A list of ARM resource IDs which are used to avoid modify azapi resources at the same time.
         * 
         * @return builder
         * 
         */
        public Builder locks(List<String> locks) {
            return locks(Output.of(locks));
        }

        /**
         * @param locks A list of ARM resource IDs which are used to avoid modify azapi resources at the same time.
         * 
         * @return builder
         * 
         */
        public Builder locks(String... locks) {
            return locks(List.of(locks));
        }

        /**
         * @param method Specifies the Http method of the azure resource action. Allowed values are `POST`, `PATCH`, `PUT` and `DELETE`. Defaults to `POST`.
         * 
         * @return builder
         * 
         */
        public Builder method(@Nullable Output<String> method) {
            $.method = method;
            return this;
        }

        /**
         * @param method Specifies the Http method of the azure resource action. Allowed values are `POST`, `PATCH`, `PUT` and `DELETE`. Defaults to `POST`.
         * 
         * @return builder
         * 
         */
        public Builder method(String method) {
            return method(Output.of(method));
        }

        /**
         * @param output The output json containing the properties specified in `response_export_values`. Here are some examples to decode json and extract the value.
         * 
         * @return builder
         * 
         */
        public Builder output(@Nullable Output<String> output) {
            $.output = output;
            return this;
        }

        /**
         * @param output The output json containing the properties specified in `response_export_values`. Here are some examples to decode json and extract the value.
         * 
         * @return builder
         * 
         */
        public Builder output(String output) {
            return output(Output.of(output));
        }

        /**
         * @param resourceId The ID of an existing azure source.
         * 
         * @return builder
         * 
         */
        public Builder resourceId(@Nullable Output<String> resourceId) {
            $.resourceId = resourceId;
            return this;
        }

        /**
         * @param resourceId The ID of an existing azure source.
         * 
         * @return builder
         * 
         */
        public Builder resourceId(String resourceId) {
            return resourceId(Output.of(resourceId));
        }

        /**
         * @param responseExportValues A list of path that needs to be exported from response body.
         * Setting it to `[&#34;*&#34;]` will export the full response body.
         * Here&#39;s an example. If it sets to `[&#34;keys&#34;]`, it will set the following json to computed property `output`.
         * ```java
         * package generated_program;
         * 
         * import com.pulumi.Context;
         * import com.pulumi.Pulumi;
         * import com.pulumi.core.Output;
         * import java.util.List;
         * import java.util.ArrayList;
         * import java.util.Map;
         * import java.io.File;
         * import java.nio.file.Files;
         * import java.nio.file.Paths;
         * 
         * public class App {
         *     public static void main(String[] args) {
         *         Pulumi.run(App::stack);
         *     }
         * 
         *     public static void stack(Context ctx) {
         *     }
         * }
         * ```
         * 
         * @return builder
         * 
         */
        public Builder responseExportValues(@Nullable Output<List<String>> responseExportValues) {
            $.responseExportValues = responseExportValues;
            return this;
        }

        /**
         * @param responseExportValues A list of path that needs to be exported from response body.
         * Setting it to `[&#34;*&#34;]` will export the full response body.
         * Here&#39;s an example. If it sets to `[&#34;keys&#34;]`, it will set the following json to computed property `output`.
         * ```java
         * package generated_program;
         * 
         * import com.pulumi.Context;
         * import com.pulumi.Pulumi;
         * import com.pulumi.core.Output;
         * import java.util.List;
         * import java.util.ArrayList;
         * import java.util.Map;
         * import java.io.File;
         * import java.nio.file.Files;
         * import java.nio.file.Paths;
         * 
         * public class App {
         *     public static void main(String[] args) {
         *         Pulumi.run(App::stack);
         *     }
         * 
         *     public static void stack(Context ctx) {
         *     }
         * }
         * ```
         * 
         * @return builder
         * 
         */
        public Builder responseExportValues(List<String> responseExportValues) {
            return responseExportValues(Output.of(responseExportValues));
        }

        /**
         * @param responseExportValues A list of path that needs to be exported from response body.
         * Setting it to `[&#34;*&#34;]` will export the full response body.
         * Here&#39;s an example. If it sets to `[&#34;keys&#34;]`, it will set the following json to computed property `output`.
         * ```java
         * package generated_program;
         * 
         * import com.pulumi.Context;
         * import com.pulumi.Pulumi;
         * import com.pulumi.core.Output;
         * import java.util.List;
         * import java.util.ArrayList;
         * import java.util.Map;
         * import java.io.File;
         * import java.nio.file.Files;
         * import java.nio.file.Paths;
         * 
         * public class App {
         *     public static void main(String[] args) {
         *         Pulumi.run(App::stack);
         *     }
         * 
         *     public static void stack(Context ctx) {
         *     }
         * }
         * ```
         * 
         * @return builder
         * 
         */
        public Builder responseExportValues(String... responseExportValues) {
            return responseExportValues(List.of(responseExportValues));
        }

        /**
         * @param type It is in a format like `&lt;resource-type&gt;@&lt;api-version&gt;`. `&lt;resource-type&gt;` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
         * `&lt;api-version&gt;` is version of the API used to manage this azure resource.
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type It is in a format like `&lt;resource-type&gt;@&lt;api-version&gt;`. `&lt;resource-type&gt;` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
         * `&lt;api-version&gt;` is version of the API used to manage this azure resource.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public ResourceActionState build() {
            return $;
        }
    }

}
