# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetResourceResult',
    'AwaitableGetResourceResult',
    'get_resource',
    'get_resource_output',
]

@pulumi.output_type
class GetResourceResult:
    """
    A collection of values returned by getResource.
    """
    def __init__(__self__, headers=None, id=None, identities=None, location=None, name=None, output=None, parent_id=None, query_parameters=None, resource_id=None, response_export_values=None, retry=None, tags=None, timeouts=None, type=None):
        if headers and not isinstance(headers, dict):
            raise TypeError("Expected argument 'headers' to be a dict")
        pulumi.set(__self__, "headers", headers)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if identities and not isinstance(identities, list):
            raise TypeError("Expected argument 'identities' to be a list")
        pulumi.set(__self__, "identities", identities)
        if location and not isinstance(location, str):
            raise TypeError("Expected argument 'location' to be a str")
        pulumi.set(__self__, "location", location)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if output and not isinstance(output, dict):
            raise TypeError("Expected argument 'output' to be a dict")
        pulumi.set(__self__, "output", output)
        if parent_id and not isinstance(parent_id, str):
            raise TypeError("Expected argument 'parent_id' to be a str")
        pulumi.set(__self__, "parent_id", parent_id)
        if query_parameters and not isinstance(query_parameters, dict):
            raise TypeError("Expected argument 'query_parameters' to be a dict")
        pulumi.set(__self__, "query_parameters", query_parameters)
        if resource_id and not isinstance(resource_id, str):
            raise TypeError("Expected argument 'resource_id' to be a str")
        pulumi.set(__self__, "resource_id", resource_id)
        if response_export_values and not isinstance(response_export_values, dict):
            raise TypeError("Expected argument 'response_export_values' to be a dict")
        pulumi.set(__self__, "response_export_values", response_export_values)
        if retry and not isinstance(retry, dict):
            raise TypeError("Expected argument 'retry' to be a dict")
        pulumi.set(__self__, "retry", retry)
        if tags and not isinstance(tags, dict):
            raise TypeError("Expected argument 'tags' to be a dict")
        pulumi.set(__self__, "tags", tags)
        if timeouts and not isinstance(timeouts, dict):
            raise TypeError("Expected argument 'timeouts' to be a dict")
        pulumi.set(__self__, "timeouts", timeouts)
        if type and not isinstance(type, str):
            raise TypeError("Expected argument 'type' to be a str")
        pulumi.set(__self__, "type", type)

    @property
    @pulumi.getter
    def headers(self) -> Optional[Mapping[str, str]]:
        return pulumi.get(self, "headers")

    @property
    @pulumi.getter
    def id(self) -> str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def identities(self) -> Sequence['outputs.GetResourceIdentityResult']:
        return pulumi.get(self, "identities")

    @property
    @pulumi.getter
    def location(self) -> str:
        return pulumi.get(self, "location")

    @property
    @pulumi.getter
    def name(self) -> str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def output(self) -> Any:
        return pulumi.get(self, "output")

    @property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> str:
        return pulumi.get(self, "parent_id")

    @property
    @pulumi.getter(name="queryParameters")
    def query_parameters(self) -> Optional[Mapping[str, Sequence[str]]]:
        return pulumi.get(self, "query_parameters")

    @property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> str:
        return pulumi.get(self, "resource_id")

    @property
    @pulumi.getter(name="responseExportValues")
    def response_export_values(self) -> Optional[Any]:
        return pulumi.get(self, "response_export_values")

    @property
    @pulumi.getter
    def retry(self) -> Optional['outputs.GetResourceRetryResult']:
        return pulumi.get(self, "retry")

    @property
    @pulumi.getter
    def tags(self) -> Mapping[str, str]:
        return pulumi.get(self, "tags")

    @property
    @pulumi.getter
    def timeouts(self) -> Optional['outputs.GetResourceTimeoutsResult']:
        return pulumi.get(self, "timeouts")

    @property
    @pulumi.getter
    def type(self) -> str:
        return pulumi.get(self, "type")


class AwaitableGetResourceResult(GetResourceResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetResourceResult(
            headers=self.headers,
            id=self.id,
            identities=self.identities,
            location=self.location,
            name=self.name,
            output=self.output,
            parent_id=self.parent_id,
            query_parameters=self.query_parameters,
            resource_id=self.resource_id,
            response_export_values=self.response_export_values,
            retry=self.retry,
            tags=self.tags,
            timeouts=self.timeouts,
            type=self.type)


def get_resource(headers: Optional[Mapping[str, str]] = None,
                 name: Optional[str] = None,
                 parent_id: Optional[str] = None,
                 query_parameters: Optional[Mapping[str, Sequence[str]]] = None,
                 resource_id: Optional[str] = None,
                 response_export_values: Optional[Any] = None,
                 retry: Optional[Union['GetResourceRetryArgs', 'GetResourceRetryArgsDict']] = None,
                 timeouts: Optional[Union['GetResourceTimeoutsArgs', 'GetResourceTimeoutsArgsDict']] = None,
                 type: Optional[str] = None,
                 opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetResourceResult:
    """
    This resource can access any existing Azure resource manager resource.## Example Usage

    ```python
    import pulumi
    import pulumi_azapi as azapi
    import pulumi_azure as azure

    example_resource_group = azure.core.ResourceGroup("exampleResourceGroup", location="west europe")
    example_registry = azure.containerservice.Registry("exampleRegistry",
        resource_group_name=example_resource_group.name,
        location=example_resource_group.location,
        sku="Premium",
        admin_enabled=False)
    example_resource = azapi.get_resource_output(name="example",
        parent_id=example_resource_group.id,
        type="Microsoft.ContainerRegistry/registries@2020-11-01-preview",
        response_export_values=[
            "properties.loginServer",
            "properties.policies.quarantinePolicy.status",
        ])
    pulumi.export("loginServer", example_resource.output["properties"]["loginServer"])
    pulumi.export("quarantinePolicy", example_resource.output["properties"]["policies"]["quarantinePolicy"]["status"])
    ```
    """
    __args__ = dict()
    __args__['headers'] = headers
    __args__['name'] = name
    __args__['parentId'] = parent_id
    __args__['queryParameters'] = query_parameters
    __args__['resourceId'] = resource_id
    __args__['responseExportValues'] = response_export_values
    __args__['retry'] = retry
    __args__['timeouts'] = timeouts
    __args__['type'] = type
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('azapi:index/getResource:getResource', __args__, opts=opts, typ=GetResourceResult).value

    return AwaitableGetResourceResult(
        headers=pulumi.get(__ret__, 'headers'),
        id=pulumi.get(__ret__, 'id'),
        identities=pulumi.get(__ret__, 'identities'),
        location=pulumi.get(__ret__, 'location'),
        name=pulumi.get(__ret__, 'name'),
        output=pulumi.get(__ret__, 'output'),
        parent_id=pulumi.get(__ret__, 'parent_id'),
        query_parameters=pulumi.get(__ret__, 'query_parameters'),
        resource_id=pulumi.get(__ret__, 'resource_id'),
        response_export_values=pulumi.get(__ret__, 'response_export_values'),
        retry=pulumi.get(__ret__, 'retry'),
        tags=pulumi.get(__ret__, 'tags'),
        timeouts=pulumi.get(__ret__, 'timeouts'),
        type=pulumi.get(__ret__, 'type'))
def get_resource_output(headers: Optional[pulumi.Input[Optional[Mapping[str, str]]]] = None,
                        name: Optional[pulumi.Input[Optional[str]]] = None,
                        parent_id: Optional[pulumi.Input[Optional[str]]] = None,
                        query_parameters: Optional[pulumi.Input[Optional[Mapping[str, Sequence[str]]]]] = None,
                        resource_id: Optional[pulumi.Input[Optional[str]]] = None,
                        response_export_values: Optional[pulumi.Input[Optional[Any]]] = None,
                        retry: Optional[pulumi.Input[Optional[Union['GetResourceRetryArgs', 'GetResourceRetryArgsDict']]]] = None,
                        timeouts: Optional[pulumi.Input[Optional[Union['GetResourceTimeoutsArgs', 'GetResourceTimeoutsArgsDict']]]] = None,
                        type: Optional[pulumi.Input[str]] = None,
                        opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetResourceResult]:
    """
    This resource can access any existing Azure resource manager resource.## Example Usage

    ```python
    import pulumi
    import pulumi_azapi as azapi
    import pulumi_azure as azure

    example_resource_group = azure.core.ResourceGroup("exampleResourceGroup", location="west europe")
    example_registry = azure.containerservice.Registry("exampleRegistry",
        resource_group_name=example_resource_group.name,
        location=example_resource_group.location,
        sku="Premium",
        admin_enabled=False)
    example_resource = azapi.get_resource_output(name="example",
        parent_id=example_resource_group.id,
        type="Microsoft.ContainerRegistry/registries@2020-11-01-preview",
        response_export_values=[
            "properties.loginServer",
            "properties.policies.quarantinePolicy.status",
        ])
    pulumi.export("loginServer", example_resource.output["properties"]["loginServer"])
    pulumi.export("quarantinePolicy", example_resource.output["properties"]["policies"]["quarantinePolicy"]["status"])
    ```
    """
    __args__ = dict()
    __args__['headers'] = headers
    __args__['name'] = name
    __args__['parentId'] = parent_id
    __args__['queryParameters'] = query_parameters
    __args__['resourceId'] = resource_id
    __args__['responseExportValues'] = response_export_values
    __args__['retry'] = retry
    __args__['timeouts'] = timeouts
    __args__['type'] = type
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('azapi:index/getResource:getResource', __args__, opts=opts, typ=GetResourceResult)
    return __ret__.apply(lambda __response__: GetResourceResult(
        headers=pulumi.get(__response__, 'headers'),
        id=pulumi.get(__response__, 'id'),
        identities=pulumi.get(__response__, 'identities'),
        location=pulumi.get(__response__, 'location'),
        name=pulumi.get(__response__, 'name'),
        output=pulumi.get(__response__, 'output'),
        parent_id=pulumi.get(__response__, 'parent_id'),
        query_parameters=pulumi.get(__response__, 'query_parameters'),
        resource_id=pulumi.get(__response__, 'resource_id'),
        response_export_values=pulumi.get(__response__, 'response_export_values'),
        retry=pulumi.get(__response__, 'retry'),
        tags=pulumi.get(__response__, 'tags'),
        timeouts=pulumi.get(__response__, 'timeouts'),
        type=pulumi.get(__response__, 'type')))
