# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._inputs import *

__all__ = ['ProviderArgs', 'Provider']

@pulumi.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 auxiliary_tenant_ids: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 client_certificate: Optional[pulumi.Input[str]] = None,
                 client_certificate_password: Optional[pulumi.Input[str]] = None,
                 client_certificate_path: Optional[pulumi.Input[str]] = None,
                 client_id: Optional[pulumi.Input[str]] = None,
                 client_id_file_path: Optional[pulumi.Input[str]] = None,
                 client_secret: Optional[pulumi.Input[str]] = None,
                 client_secret_file_path: Optional[pulumi.Input[str]] = None,
                 custom_correlation_request_id: Optional[pulumi.Input[str]] = None,
                 default_location: Optional[pulumi.Input[str]] = None,
                 default_name: Optional[pulumi.Input[str]] = None,
                 default_tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 disable_correlation_request_id: Optional[pulumi.Input[bool]] = None,
                 disable_default_output: Optional[pulumi.Input[bool]] = None,
                 disable_terraform_partner_id: Optional[pulumi.Input[bool]] = None,
                 enable_preflight: Optional[pulumi.Input[bool]] = None,
                 endpoints: Optional[pulumi.Input[Sequence[pulumi.Input['ProviderEndpointArgs']]]] = None,
                 environment: Optional[pulumi.Input[str]] = None,
                 maximum_busy_retry_attempts: Optional[pulumi.Input[int]] = None,
                 oidc_azure_service_connection_id: Optional[pulumi.Input[str]] = None,
                 oidc_request_token: Optional[pulumi.Input[str]] = None,
                 oidc_request_url: Optional[pulumi.Input[str]] = None,
                 oidc_token: Optional[pulumi.Input[str]] = None,
                 oidc_token_file_path: Optional[pulumi.Input[str]] = None,
                 partner_id: Optional[pulumi.Input[str]] = None,
                 skip_provider_registration: Optional[pulumi.Input[bool]] = None,
                 subscription_id: Optional[pulumi.Input[str]] = None,
                 tenant_id: Optional[pulumi.Input[str]] = None,
                 use_aks_workload_identity: Optional[pulumi.Input[bool]] = None,
                 use_cli: Optional[pulumi.Input[bool]] = None,
                 use_msi: Optional[pulumi.Input[bool]] = None,
                 use_oidc: Optional[pulumi.Input[bool]] = None):
        """
        The set of arguments for constructing a Provider resource.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] auxiliary_tenant_ids: List of auxiliary Tenant IDs required for multi-tenancy and cross-tenant scenarios. This can also be sourced from the
               `ARM_AUXILIARY_TENANT_IDS` Environment Variable.
        :param pulumi.Input[str] client_certificate: A base64-encoded PKCS#12 bundle to be used as the client certificate for authentication. This can also be sourced from
               the `ARM_CLIENT_CERTIFICATE` environment variable.
        :param pulumi.Input[str] client_certificate_password: The password associated with the Client Certificate. This can also be sourced from the `ARM_CLIENT_CERTIFICATE_PASSWORD`
               Environment Variable.
        :param pulumi.Input[str] client_certificate_path: The path to the Client Certificate associated with the Service Principal which should be used. This can also be sourced
               from the `ARM_CLIENT_CERTIFICATE_PATH` Environment Variable.
        :param pulumi.Input[str] client_id: The Client ID which should be used. This can also be sourced from the `ARM_CLIENT_ID` Environment Variable.
        :param pulumi.Input[str] client_id_file_path: The path to a file containing the Client ID which should be used. This can also be sourced from the
               `ARM_CLIENT_ID_FILE_PATH` Environment Variable.
        :param pulumi.Input[str] client_secret: The Client Secret which should be used. This can also be sourced from the `ARM_CLIENT_SECRET` Environment Variable.
        :param pulumi.Input[str] client_secret_file_path: The path to a file containing the Client Secret which should be used. For use When authenticating as a Service Principal
               using a Client Secret. This can also be sourced from the `ARM_CLIENT_SECRET_FILE_PATH` Environment Variable.
        :param pulumi.Input[str] custom_correlation_request_id: The value of the `x-ms-correlation-request-id` header, otherwise an auto-generated UUID will be used. This can also be
               sourced from the `ARM_CORRELATION_REQUEST_ID` environment variable.
        :param pulumi.Input[str] default_location: The default Azure Region where the azure resource should exist. The `location` in each resource block can override the
               `default_location`. Changing this forces new resources to be created.
        :param pulumi.Input[str] default_name: The default name to create the azure resource. The `name` in each resource block can override the `default_name`.
               Changing this forces new resources to be created.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] default_tags: A mapping of tags which should be assigned to the azure resource as default tags. The`tags` in each resource block can
               override the `default_tags`.
        :param pulumi.Input[bool] disable_correlation_request_id: This will disable the x-ms-correlation-request-id header.
        :param pulumi.Input[bool] disable_default_output: Disable default output. The default is false. When set to false, the provider will output the read-only properties if
               `response_export_values` is not specified in the resource block. When set to true, the provider will disable this
               output. This can also be sourced from the `ARM_DISABLE_DEFAULT_OUTPUT` Environment Variable.
        :param pulumi.Input[bool] enable_preflight: Enable Preflight Validation. The default is false. When set to true, the provider will use Preflight to do static
               validation before really deploying a new resource. When set to false, the provider will disable this validation. This
               can also be sourced from the `ARM_ENABLE_PREFLIGHT` Environment Variable.
        :param pulumi.Input[Sequence[pulumi.Input['ProviderEndpointArgs']]] endpoints: The Azure API Endpoint Configuration.
        :param pulumi.Input[str] environment: The Cloud Environment which should be used. Possible values are `public`, `usgovernment` and `china`. Defaults to
               `public`. This can also be sourced from the `ARM_ENVIRONMENT` Environment Variable.
        :param pulumi.Input[int] maximum_busy_retry_attempts: The maximum number of retries to attempt if the Azure API returns an HTTP 408, 429, 500, 502, 503, or 504 response. The
               default is `3`. The resource-specific retry configuration may additionally be used to retry on other errors and
               conditions.
        :param pulumi.Input[str] oidc_azure_service_connection_id: The Azure Pipelines Service Connection ID to use for authentication. This can also be sourced from the
               `ARM_ADO_PIPELINE_SERVICE_CONNECTION_ID` or `ARM_OIDC_AZURE_SERVICE_CONNECTION_ID` Environment Variables.
        :param pulumi.Input[str] oidc_request_token: The bearer token for the request to the OIDC provider. This can also be sourced from the `ARM_OIDC_REQUEST_TOKEN` or
               `ACTIONS_ID_TOKEN_REQUEST_TOKEN` Environment Variables.
        :param pulumi.Input[str] oidc_request_url: The URL for the OIDC provider from which to request an ID token. This can also be sourced from the
               `ARM_OIDC_REQUEST_URL` or `ACTIONS_ID_TOKEN_REQUEST_URL` Environment Variables.
        :param pulumi.Input[str] oidc_token: The ID token when authenticating using OpenID Connect (OIDC). This can also be sourced from the `ARM_OIDC_TOKEN`
               environment Variable.
        :param pulumi.Input[str] oidc_token_file_path: The path to a file containing an ID token when authenticating using OpenID Connect (OIDC). This can also be sourced from
               the `ARM_OIDC_TOKEN_FILE_PATH` environment Variable.
        :param pulumi.Input[str] partner_id: A GUID/UUID that is
               [registered](https://docs.microsoft.com/azure/marketplace/azure-partner-customer-usage-attribution#register-guids-and-offers)
               with Microsoft to facilitate partner resource usage attribution. This can also be sourced from the `ARM_PARTNER_ID`
               Environment Variable.
        :param pulumi.Input[bool] skip_provider_registration: Should the Provider skip registering the Resource Providers it supports? This can also be sourced from the
               `ARM_SKIP_PROVIDER_REGISTRATION` Environment Variable. Defaults to `false`.
        :param pulumi.Input[str] subscription_id: The Subscription ID which should be used. This can also be sourced from the `ARM_SUBSCRIPTION_ID` Environment Variable.
        :param pulumi.Input[str] tenant_id: The Tenant ID should be used. This can also be sourced from the `ARM_TENANT_ID` Environment Variable.
        :param pulumi.Input[bool] use_aks_workload_identity: Should AKS Workload Identity be used for Authentication? This can also be sourced from the
               `ARM_USE_AKS_WORKLOAD_IDENTITY` Environment Variable. Defaults to `false`. When set, `client_id`, `tenant_id` and
               `oidc_token_file_path` will be detected from the environment and do not need to be specified.
        :param pulumi.Input[bool] use_cli: Should Azure CLI be used for authentication? This can also be sourced from the `ARM_USE_CLI` environment variable.
               Defaults to `true`.
        :param pulumi.Input[bool] use_msi: Should Managed Identity be used for Authentication? This can also be sourced from the `ARM_USE_MSI` Environment
               Variable. Defaults to `false`.
        :param pulumi.Input[bool] use_oidc: Should OIDC be used for Authentication? This can also be sourced from the `ARM_USE_OIDC` Environment Variable. Defaults
               to `false`.
        """
        if auxiliary_tenant_ids is not None:
            pulumi.set(__self__, "auxiliary_tenant_ids", auxiliary_tenant_ids)
        if client_certificate is not None:
            pulumi.set(__self__, "client_certificate", client_certificate)
        if client_certificate_password is not None:
            pulumi.set(__self__, "client_certificate_password", client_certificate_password)
        if client_certificate_path is not None:
            pulumi.set(__self__, "client_certificate_path", client_certificate_path)
        if client_id is not None:
            pulumi.set(__self__, "client_id", client_id)
        if client_id_file_path is not None:
            pulumi.set(__self__, "client_id_file_path", client_id_file_path)
        if client_secret is not None:
            pulumi.set(__self__, "client_secret", client_secret)
        if client_secret_file_path is not None:
            pulumi.set(__self__, "client_secret_file_path", client_secret_file_path)
        if custom_correlation_request_id is not None:
            pulumi.set(__self__, "custom_correlation_request_id", custom_correlation_request_id)
        if default_location is not None:
            pulumi.set(__self__, "default_location", default_location)
        if default_name is not None:
            pulumi.set(__self__, "default_name", default_name)
        if default_tags is not None:
            pulumi.set(__self__, "default_tags", default_tags)
        if disable_correlation_request_id is not None:
            pulumi.set(__self__, "disable_correlation_request_id", disable_correlation_request_id)
        if disable_default_output is not None:
            pulumi.set(__self__, "disable_default_output", disable_default_output)
        if disable_terraform_partner_id is not None:
            pulumi.set(__self__, "disable_terraform_partner_id", disable_terraform_partner_id)
        if enable_preflight is not None:
            pulumi.set(__self__, "enable_preflight", enable_preflight)
        if endpoints is not None:
            pulumi.set(__self__, "endpoints", endpoints)
        if environment is not None:
            pulumi.set(__self__, "environment", environment)
        if maximum_busy_retry_attempts is not None:
            pulumi.set(__self__, "maximum_busy_retry_attempts", maximum_busy_retry_attempts)
        if oidc_azure_service_connection_id is not None:
            pulumi.set(__self__, "oidc_azure_service_connection_id", oidc_azure_service_connection_id)
        if oidc_request_token is not None:
            pulumi.set(__self__, "oidc_request_token", oidc_request_token)
        if oidc_request_url is not None:
            pulumi.set(__self__, "oidc_request_url", oidc_request_url)
        if oidc_token is not None:
            pulumi.set(__self__, "oidc_token", oidc_token)
        if oidc_token_file_path is not None:
            pulumi.set(__self__, "oidc_token_file_path", oidc_token_file_path)
        if partner_id is not None:
            pulumi.set(__self__, "partner_id", partner_id)
        if skip_provider_registration is not None:
            pulumi.set(__self__, "skip_provider_registration", skip_provider_registration)
        if subscription_id is not None:
            pulumi.set(__self__, "subscription_id", subscription_id)
        if tenant_id is not None:
            pulumi.set(__self__, "tenant_id", tenant_id)
        if use_aks_workload_identity is not None:
            pulumi.set(__self__, "use_aks_workload_identity", use_aks_workload_identity)
        if use_cli is not None:
            pulumi.set(__self__, "use_cli", use_cli)
        if use_msi is not None:
            pulumi.set(__self__, "use_msi", use_msi)
        if use_oidc is not None:
            pulumi.set(__self__, "use_oidc", use_oidc)

    @property
    @pulumi.getter(name="auxiliaryTenantIds")
    def auxiliary_tenant_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        List of auxiliary Tenant IDs required for multi-tenancy and cross-tenant scenarios. This can also be sourced from the
        `ARM_AUXILIARY_TENANT_IDS` Environment Variable.
        """
        return pulumi.get(self, "auxiliary_tenant_ids")

    @auxiliary_tenant_ids.setter
    def auxiliary_tenant_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "auxiliary_tenant_ids", value)

    @property
    @pulumi.getter(name="clientCertificate")
    def client_certificate(self) -> Optional[pulumi.Input[str]]:
        """
        A base64-encoded PKCS#12 bundle to be used as the client certificate for authentication. This can also be sourced from
        the `ARM_CLIENT_CERTIFICATE` environment variable.
        """
        return pulumi.get(self, "client_certificate")

    @client_certificate.setter
    def client_certificate(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "client_certificate", value)

    @property
    @pulumi.getter(name="clientCertificatePassword")
    def client_certificate_password(self) -> Optional[pulumi.Input[str]]:
        """
        The password associated with the Client Certificate. This can also be sourced from the `ARM_CLIENT_CERTIFICATE_PASSWORD`
        Environment Variable.
        """
        return pulumi.get(self, "client_certificate_password")

    @client_certificate_password.setter
    def client_certificate_password(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "client_certificate_password", value)

    @property
    @pulumi.getter(name="clientCertificatePath")
    def client_certificate_path(self) -> Optional[pulumi.Input[str]]:
        """
        The path to the Client Certificate associated with the Service Principal which should be used. This can also be sourced
        from the `ARM_CLIENT_CERTIFICATE_PATH` Environment Variable.
        """
        return pulumi.get(self, "client_certificate_path")

    @client_certificate_path.setter
    def client_certificate_path(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "client_certificate_path", value)

    @property
    @pulumi.getter(name="clientId")
    def client_id(self) -> Optional[pulumi.Input[str]]:
        """
        The Client ID which should be used. This can also be sourced from the `ARM_CLIENT_ID` Environment Variable.
        """
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "client_id", value)

    @property
    @pulumi.getter(name="clientIdFilePath")
    def client_id_file_path(self) -> Optional[pulumi.Input[str]]:
        """
        The path to a file containing the Client ID which should be used. This can also be sourced from the
        `ARM_CLIENT_ID_FILE_PATH` Environment Variable.
        """
        return pulumi.get(self, "client_id_file_path")

    @client_id_file_path.setter
    def client_id_file_path(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "client_id_file_path", value)

    @property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> Optional[pulumi.Input[str]]:
        """
        The Client Secret which should be used. This can also be sourced from the `ARM_CLIENT_SECRET` Environment Variable.
        """
        return pulumi.get(self, "client_secret")

    @client_secret.setter
    def client_secret(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "client_secret", value)

    @property
    @pulumi.getter(name="clientSecretFilePath")
    def client_secret_file_path(self) -> Optional[pulumi.Input[str]]:
        """
        The path to a file containing the Client Secret which should be used. For use When authenticating as a Service Principal
        using a Client Secret. This can also be sourced from the `ARM_CLIENT_SECRET_FILE_PATH` Environment Variable.
        """
        return pulumi.get(self, "client_secret_file_path")

    @client_secret_file_path.setter
    def client_secret_file_path(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "client_secret_file_path", value)

    @property
    @pulumi.getter(name="customCorrelationRequestId")
    def custom_correlation_request_id(self) -> Optional[pulumi.Input[str]]:
        """
        The value of the `x-ms-correlation-request-id` header, otherwise an auto-generated UUID will be used. This can also be
        sourced from the `ARM_CORRELATION_REQUEST_ID` environment variable.
        """
        return pulumi.get(self, "custom_correlation_request_id")

    @custom_correlation_request_id.setter
    def custom_correlation_request_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "custom_correlation_request_id", value)

    @property
    @pulumi.getter(name="defaultLocation")
    def default_location(self) -> Optional[pulumi.Input[str]]:
        """
        The default Azure Region where the azure resource should exist. The `location` in each resource block can override the
        `default_location`. Changing this forces new resources to be created.
        """
        return pulumi.get(self, "default_location")

    @default_location.setter
    def default_location(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "default_location", value)

    @property
    @pulumi.getter(name="defaultName")
    def default_name(self) -> Optional[pulumi.Input[str]]:
        """
        The default name to create the azure resource. The `name` in each resource block can override the `default_name`.
        Changing this forces new resources to be created.
        """
        return pulumi.get(self, "default_name")

    @default_name.setter
    def default_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "default_name", value)

    @property
    @pulumi.getter(name="defaultTags")
    def default_tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        A mapping of tags which should be assigned to the azure resource as default tags. The`tags` in each resource block can
        override the `default_tags`.
        """
        return pulumi.get(self, "default_tags")

    @default_tags.setter
    def default_tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "default_tags", value)

    @property
    @pulumi.getter(name="disableCorrelationRequestId")
    def disable_correlation_request_id(self) -> Optional[pulumi.Input[bool]]:
        """
        This will disable the x-ms-correlation-request-id header.
        """
        return pulumi.get(self, "disable_correlation_request_id")

    @disable_correlation_request_id.setter
    def disable_correlation_request_id(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "disable_correlation_request_id", value)

    @property
    @pulumi.getter(name="disableDefaultOutput")
    def disable_default_output(self) -> Optional[pulumi.Input[bool]]:
        """
        Disable default output. The default is false. When set to false, the provider will output the read-only properties if
        `response_export_values` is not specified in the resource block. When set to true, the provider will disable this
        output. This can also be sourced from the `ARM_DISABLE_DEFAULT_OUTPUT` Environment Variable.
        """
        return pulumi.get(self, "disable_default_output")

    @disable_default_output.setter
    def disable_default_output(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "disable_default_output", value)

    @property
    @pulumi.getter(name="disableTerraformPartnerId")
    def disable_terraform_partner_id(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "disable_terraform_partner_id")

    @disable_terraform_partner_id.setter
    def disable_terraform_partner_id(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "disable_terraform_partner_id", value)

    @property
    @pulumi.getter(name="enablePreflight")
    def enable_preflight(self) -> Optional[pulumi.Input[bool]]:
        """
        Enable Preflight Validation. The default is false. When set to true, the provider will use Preflight to do static
        validation before really deploying a new resource. When set to false, the provider will disable this validation. This
        can also be sourced from the `ARM_ENABLE_PREFLIGHT` Environment Variable.
        """
        return pulumi.get(self, "enable_preflight")

    @enable_preflight.setter
    def enable_preflight(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enable_preflight", value)

    @property
    @pulumi.getter
    def endpoints(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ProviderEndpointArgs']]]]:
        """
        The Azure API Endpoint Configuration.
        """
        return pulumi.get(self, "endpoints")

    @endpoints.setter
    def endpoints(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ProviderEndpointArgs']]]]):
        pulumi.set(self, "endpoints", value)

    @property
    @pulumi.getter
    def environment(self) -> Optional[pulumi.Input[str]]:
        """
        The Cloud Environment which should be used. Possible values are `public`, `usgovernment` and `china`. Defaults to
        `public`. This can also be sourced from the `ARM_ENVIRONMENT` Environment Variable.
        """
        return pulumi.get(self, "environment")

    @environment.setter
    def environment(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "environment", value)

    @property
    @pulumi.getter(name="maximumBusyRetryAttempts")
    def maximum_busy_retry_attempts(self) -> Optional[pulumi.Input[int]]:
        """
        The maximum number of retries to attempt if the Azure API returns an HTTP 408, 429, 500, 502, 503, or 504 response. The
        default is `3`. The resource-specific retry configuration may additionally be used to retry on other errors and
        conditions.
        """
        return pulumi.get(self, "maximum_busy_retry_attempts")

    @maximum_busy_retry_attempts.setter
    def maximum_busy_retry_attempts(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "maximum_busy_retry_attempts", value)

    @property
    @pulumi.getter(name="oidcAzureServiceConnectionId")
    def oidc_azure_service_connection_id(self) -> Optional[pulumi.Input[str]]:
        """
        The Azure Pipelines Service Connection ID to use for authentication. This can also be sourced from the
        `ARM_ADO_PIPELINE_SERVICE_CONNECTION_ID` or `ARM_OIDC_AZURE_SERVICE_CONNECTION_ID` Environment Variables.
        """
        return pulumi.get(self, "oidc_azure_service_connection_id")

    @oidc_azure_service_connection_id.setter
    def oidc_azure_service_connection_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "oidc_azure_service_connection_id", value)

    @property
    @pulumi.getter(name="oidcRequestToken")
    def oidc_request_token(self) -> Optional[pulumi.Input[str]]:
        """
        The bearer token for the request to the OIDC provider. This can also be sourced from the `ARM_OIDC_REQUEST_TOKEN` or
        `ACTIONS_ID_TOKEN_REQUEST_TOKEN` Environment Variables.
        """
        return pulumi.get(self, "oidc_request_token")

    @oidc_request_token.setter
    def oidc_request_token(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "oidc_request_token", value)

    @property
    @pulumi.getter(name="oidcRequestUrl")
    def oidc_request_url(self) -> Optional[pulumi.Input[str]]:
        """
        The URL for the OIDC provider from which to request an ID token. This can also be sourced from the
        `ARM_OIDC_REQUEST_URL` or `ACTIONS_ID_TOKEN_REQUEST_URL` Environment Variables.
        """
        return pulumi.get(self, "oidc_request_url")

    @oidc_request_url.setter
    def oidc_request_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "oidc_request_url", value)

    @property
    @pulumi.getter(name="oidcToken")
    def oidc_token(self) -> Optional[pulumi.Input[str]]:
        """
        The ID token when authenticating using OpenID Connect (OIDC). This can also be sourced from the `ARM_OIDC_TOKEN`
        environment Variable.
        """
        return pulumi.get(self, "oidc_token")

    @oidc_token.setter
    def oidc_token(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "oidc_token", value)

    @property
    @pulumi.getter(name="oidcTokenFilePath")
    def oidc_token_file_path(self) -> Optional[pulumi.Input[str]]:
        """
        The path to a file containing an ID token when authenticating using OpenID Connect (OIDC). This can also be sourced from
        the `ARM_OIDC_TOKEN_FILE_PATH` environment Variable.
        """
        return pulumi.get(self, "oidc_token_file_path")

    @oidc_token_file_path.setter
    def oidc_token_file_path(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "oidc_token_file_path", value)

    @property
    @pulumi.getter(name="partnerId")
    def partner_id(self) -> Optional[pulumi.Input[str]]:
        """
        A GUID/UUID that is
        [registered](https://docs.microsoft.com/azure/marketplace/azure-partner-customer-usage-attribution#register-guids-and-offers)
        with Microsoft to facilitate partner resource usage attribution. This can also be sourced from the `ARM_PARTNER_ID`
        Environment Variable.
        """
        return pulumi.get(self, "partner_id")

    @partner_id.setter
    def partner_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "partner_id", value)

    @property
    @pulumi.getter(name="skipProviderRegistration")
    def skip_provider_registration(self) -> Optional[pulumi.Input[bool]]:
        """
        Should the Provider skip registering the Resource Providers it supports? This can also be sourced from the
        `ARM_SKIP_PROVIDER_REGISTRATION` Environment Variable. Defaults to `false`.
        """
        return pulumi.get(self, "skip_provider_registration")

    @skip_provider_registration.setter
    def skip_provider_registration(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "skip_provider_registration", value)

    @property
    @pulumi.getter(name="subscriptionId")
    def subscription_id(self) -> Optional[pulumi.Input[str]]:
        """
        The Subscription ID which should be used. This can also be sourced from the `ARM_SUBSCRIPTION_ID` Environment Variable.
        """
        return pulumi.get(self, "subscription_id")

    @subscription_id.setter
    def subscription_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "subscription_id", value)

    @property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> Optional[pulumi.Input[str]]:
        """
        The Tenant ID should be used. This can also be sourced from the `ARM_TENANT_ID` Environment Variable.
        """
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "tenant_id", value)

    @property
    @pulumi.getter(name="useAksWorkloadIdentity")
    def use_aks_workload_identity(self) -> Optional[pulumi.Input[bool]]:
        """
        Should AKS Workload Identity be used for Authentication? This can also be sourced from the
        `ARM_USE_AKS_WORKLOAD_IDENTITY` Environment Variable. Defaults to `false`. When set, `client_id`, `tenant_id` and
        `oidc_token_file_path` will be detected from the environment and do not need to be specified.
        """
        return pulumi.get(self, "use_aks_workload_identity")

    @use_aks_workload_identity.setter
    def use_aks_workload_identity(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "use_aks_workload_identity", value)

    @property
    @pulumi.getter(name="useCli")
    def use_cli(self) -> Optional[pulumi.Input[bool]]:
        """
        Should Azure CLI be used for authentication? This can also be sourced from the `ARM_USE_CLI` environment variable.
        Defaults to `true`.
        """
        return pulumi.get(self, "use_cli")

    @use_cli.setter
    def use_cli(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "use_cli", value)

    @property
    @pulumi.getter(name="useMsi")
    def use_msi(self) -> Optional[pulumi.Input[bool]]:
        """
        Should Managed Identity be used for Authentication? This can also be sourced from the `ARM_USE_MSI` Environment
        Variable. Defaults to `false`.
        """
        return pulumi.get(self, "use_msi")

    @use_msi.setter
    def use_msi(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "use_msi", value)

    @property
    @pulumi.getter(name="useOidc")
    def use_oidc(self) -> Optional[pulumi.Input[bool]]:
        """
        Should OIDC be used for Authentication? This can also be sourced from the `ARM_USE_OIDC` Environment Variable. Defaults
        to `false`.
        """
        return pulumi.get(self, "use_oidc")

    @use_oidc.setter
    def use_oidc(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "use_oidc", value)


class Provider(pulumi.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auxiliary_tenant_ids: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 client_certificate: Optional[pulumi.Input[str]] = None,
                 client_certificate_password: Optional[pulumi.Input[str]] = None,
                 client_certificate_path: Optional[pulumi.Input[str]] = None,
                 client_id: Optional[pulumi.Input[str]] = None,
                 client_id_file_path: Optional[pulumi.Input[str]] = None,
                 client_secret: Optional[pulumi.Input[str]] = None,
                 client_secret_file_path: Optional[pulumi.Input[str]] = None,
                 custom_correlation_request_id: Optional[pulumi.Input[str]] = None,
                 default_location: Optional[pulumi.Input[str]] = None,
                 default_name: Optional[pulumi.Input[str]] = None,
                 default_tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 disable_correlation_request_id: Optional[pulumi.Input[bool]] = None,
                 disable_default_output: Optional[pulumi.Input[bool]] = None,
                 disable_terraform_partner_id: Optional[pulumi.Input[bool]] = None,
                 enable_preflight: Optional[pulumi.Input[bool]] = None,
                 endpoints: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ProviderEndpointArgs', 'ProviderEndpointArgsDict']]]]] = None,
                 environment: Optional[pulumi.Input[str]] = None,
                 maximum_busy_retry_attempts: Optional[pulumi.Input[int]] = None,
                 oidc_azure_service_connection_id: Optional[pulumi.Input[str]] = None,
                 oidc_request_token: Optional[pulumi.Input[str]] = None,
                 oidc_request_url: Optional[pulumi.Input[str]] = None,
                 oidc_token: Optional[pulumi.Input[str]] = None,
                 oidc_token_file_path: Optional[pulumi.Input[str]] = None,
                 partner_id: Optional[pulumi.Input[str]] = None,
                 skip_provider_registration: Optional[pulumi.Input[bool]] = None,
                 subscription_id: Optional[pulumi.Input[str]] = None,
                 tenant_id: Optional[pulumi.Input[str]] = None,
                 use_aks_workload_identity: Optional[pulumi.Input[bool]] = None,
                 use_cli: Optional[pulumi.Input[bool]] = None,
                 use_msi: Optional[pulumi.Input[bool]] = None,
                 use_oidc: Optional[pulumi.Input[bool]] = None,
                 __props__=None):
        """
        The provider type for the azapi package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] auxiliary_tenant_ids: List of auxiliary Tenant IDs required for multi-tenancy and cross-tenant scenarios. This can also be sourced from the
               `ARM_AUXILIARY_TENANT_IDS` Environment Variable.
        :param pulumi.Input[str] client_certificate: A base64-encoded PKCS#12 bundle to be used as the client certificate for authentication. This can also be sourced from
               the `ARM_CLIENT_CERTIFICATE` environment variable.
        :param pulumi.Input[str] client_certificate_password: The password associated with the Client Certificate. This can also be sourced from the `ARM_CLIENT_CERTIFICATE_PASSWORD`
               Environment Variable.
        :param pulumi.Input[str] client_certificate_path: The path to the Client Certificate associated with the Service Principal which should be used. This can also be sourced
               from the `ARM_CLIENT_CERTIFICATE_PATH` Environment Variable.
        :param pulumi.Input[str] client_id: The Client ID which should be used. This can also be sourced from the `ARM_CLIENT_ID` Environment Variable.
        :param pulumi.Input[str] client_id_file_path: The path to a file containing the Client ID which should be used. This can also be sourced from the
               `ARM_CLIENT_ID_FILE_PATH` Environment Variable.
        :param pulumi.Input[str] client_secret: The Client Secret which should be used. This can also be sourced from the `ARM_CLIENT_SECRET` Environment Variable.
        :param pulumi.Input[str] client_secret_file_path: The path to a file containing the Client Secret which should be used. For use When authenticating as a Service Principal
               using a Client Secret. This can also be sourced from the `ARM_CLIENT_SECRET_FILE_PATH` Environment Variable.
        :param pulumi.Input[str] custom_correlation_request_id: The value of the `x-ms-correlation-request-id` header, otherwise an auto-generated UUID will be used. This can also be
               sourced from the `ARM_CORRELATION_REQUEST_ID` environment variable.
        :param pulumi.Input[str] default_location: The default Azure Region where the azure resource should exist. The `location` in each resource block can override the
               `default_location`. Changing this forces new resources to be created.
        :param pulumi.Input[str] default_name: The default name to create the azure resource. The `name` in each resource block can override the `default_name`.
               Changing this forces new resources to be created.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] default_tags: A mapping of tags which should be assigned to the azure resource as default tags. The`tags` in each resource block can
               override the `default_tags`.
        :param pulumi.Input[bool] disable_correlation_request_id: This will disable the x-ms-correlation-request-id header.
        :param pulumi.Input[bool] disable_default_output: Disable default output. The default is false. When set to false, the provider will output the read-only properties if
               `response_export_values` is not specified in the resource block. When set to true, the provider will disable this
               output. This can also be sourced from the `ARM_DISABLE_DEFAULT_OUTPUT` Environment Variable.
        :param pulumi.Input[bool] enable_preflight: Enable Preflight Validation. The default is false. When set to true, the provider will use Preflight to do static
               validation before really deploying a new resource. When set to false, the provider will disable this validation. This
               can also be sourced from the `ARM_ENABLE_PREFLIGHT` Environment Variable.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ProviderEndpointArgs', 'ProviderEndpointArgsDict']]]] endpoints: The Azure API Endpoint Configuration.
        :param pulumi.Input[str] environment: The Cloud Environment which should be used. Possible values are `public`, `usgovernment` and `china`. Defaults to
               `public`. This can also be sourced from the `ARM_ENVIRONMENT` Environment Variable.
        :param pulumi.Input[int] maximum_busy_retry_attempts: The maximum number of retries to attempt if the Azure API returns an HTTP 408, 429, 500, 502, 503, or 504 response. The
               default is `3`. The resource-specific retry configuration may additionally be used to retry on other errors and
               conditions.
        :param pulumi.Input[str] oidc_azure_service_connection_id: The Azure Pipelines Service Connection ID to use for authentication. This can also be sourced from the
               `ARM_ADO_PIPELINE_SERVICE_CONNECTION_ID` or `ARM_OIDC_AZURE_SERVICE_CONNECTION_ID` Environment Variables.
        :param pulumi.Input[str] oidc_request_token: The bearer token for the request to the OIDC provider. This can also be sourced from the `ARM_OIDC_REQUEST_TOKEN` or
               `ACTIONS_ID_TOKEN_REQUEST_TOKEN` Environment Variables.
        :param pulumi.Input[str] oidc_request_url: The URL for the OIDC provider from which to request an ID token. This can also be sourced from the
               `ARM_OIDC_REQUEST_URL` or `ACTIONS_ID_TOKEN_REQUEST_URL` Environment Variables.
        :param pulumi.Input[str] oidc_token: The ID token when authenticating using OpenID Connect (OIDC). This can also be sourced from the `ARM_OIDC_TOKEN`
               environment Variable.
        :param pulumi.Input[str] oidc_token_file_path: The path to a file containing an ID token when authenticating using OpenID Connect (OIDC). This can also be sourced from
               the `ARM_OIDC_TOKEN_FILE_PATH` environment Variable.
        :param pulumi.Input[str] partner_id: A GUID/UUID that is
               [registered](https://docs.microsoft.com/azure/marketplace/azure-partner-customer-usage-attribution#register-guids-and-offers)
               with Microsoft to facilitate partner resource usage attribution. This can also be sourced from the `ARM_PARTNER_ID`
               Environment Variable.
        :param pulumi.Input[bool] skip_provider_registration: Should the Provider skip registering the Resource Providers it supports? This can also be sourced from the
               `ARM_SKIP_PROVIDER_REGISTRATION` Environment Variable. Defaults to `false`.
        :param pulumi.Input[str] subscription_id: The Subscription ID which should be used. This can also be sourced from the `ARM_SUBSCRIPTION_ID` Environment Variable.
        :param pulumi.Input[str] tenant_id: The Tenant ID should be used. This can also be sourced from the `ARM_TENANT_ID` Environment Variable.
        :param pulumi.Input[bool] use_aks_workload_identity: Should AKS Workload Identity be used for Authentication? This can also be sourced from the
               `ARM_USE_AKS_WORKLOAD_IDENTITY` Environment Variable. Defaults to `false`. When set, `client_id`, `tenant_id` and
               `oidc_token_file_path` will be detected from the environment and do not need to be specified.
        :param pulumi.Input[bool] use_cli: Should Azure CLI be used for authentication? This can also be sourced from the `ARM_USE_CLI` environment variable.
               Defaults to `true`.
        :param pulumi.Input[bool] use_msi: Should Managed Identity be used for Authentication? This can also be sourced from the `ARM_USE_MSI` Environment
               Variable. Defaults to `false`.
        :param pulumi.Input[bool] use_oidc: Should OIDC be used for Authentication? This can also be sourced from the `ARM_USE_OIDC` Environment Variable. Defaults
               to `false`.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProviderArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The provider type for the azapi package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.

        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auxiliary_tenant_ids: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 client_certificate: Optional[pulumi.Input[str]] = None,
                 client_certificate_password: Optional[pulumi.Input[str]] = None,
                 client_certificate_path: Optional[pulumi.Input[str]] = None,
                 client_id: Optional[pulumi.Input[str]] = None,
                 client_id_file_path: Optional[pulumi.Input[str]] = None,
                 client_secret: Optional[pulumi.Input[str]] = None,
                 client_secret_file_path: Optional[pulumi.Input[str]] = None,
                 custom_correlation_request_id: Optional[pulumi.Input[str]] = None,
                 default_location: Optional[pulumi.Input[str]] = None,
                 default_name: Optional[pulumi.Input[str]] = None,
                 default_tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 disable_correlation_request_id: Optional[pulumi.Input[bool]] = None,
                 disable_default_output: Optional[pulumi.Input[bool]] = None,
                 disable_terraform_partner_id: Optional[pulumi.Input[bool]] = None,
                 enable_preflight: Optional[pulumi.Input[bool]] = None,
                 endpoints: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ProviderEndpointArgs', 'ProviderEndpointArgsDict']]]]] = None,
                 environment: Optional[pulumi.Input[str]] = None,
                 maximum_busy_retry_attempts: Optional[pulumi.Input[int]] = None,
                 oidc_azure_service_connection_id: Optional[pulumi.Input[str]] = None,
                 oidc_request_token: Optional[pulumi.Input[str]] = None,
                 oidc_request_url: Optional[pulumi.Input[str]] = None,
                 oidc_token: Optional[pulumi.Input[str]] = None,
                 oidc_token_file_path: Optional[pulumi.Input[str]] = None,
                 partner_id: Optional[pulumi.Input[str]] = None,
                 skip_provider_registration: Optional[pulumi.Input[bool]] = None,
                 subscription_id: Optional[pulumi.Input[str]] = None,
                 tenant_id: Optional[pulumi.Input[str]] = None,
                 use_aks_workload_identity: Optional[pulumi.Input[bool]] = None,
                 use_cli: Optional[pulumi.Input[bool]] = None,
                 use_msi: Optional[pulumi.Input[bool]] = None,
                 use_oidc: Optional[pulumi.Input[bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            __props__.__dict__["auxiliary_tenant_ids"] = pulumi.Output.from_input(auxiliary_tenant_ids).apply(pulumi.runtime.to_json) if auxiliary_tenant_ids is not None else None
            __props__.__dict__["client_certificate"] = client_certificate
            __props__.__dict__["client_certificate_password"] = client_certificate_password
            __props__.__dict__["client_certificate_path"] = client_certificate_path
            __props__.__dict__["client_id"] = client_id
            __props__.__dict__["client_id_file_path"] = client_id_file_path
            __props__.__dict__["client_secret"] = client_secret
            __props__.__dict__["client_secret_file_path"] = client_secret_file_path
            __props__.__dict__["custom_correlation_request_id"] = custom_correlation_request_id
            __props__.__dict__["default_location"] = default_location
            __props__.__dict__["default_name"] = default_name
            __props__.__dict__["default_tags"] = pulumi.Output.from_input(default_tags).apply(pulumi.runtime.to_json) if default_tags is not None else None
            __props__.__dict__["disable_correlation_request_id"] = pulumi.Output.from_input(disable_correlation_request_id).apply(pulumi.runtime.to_json) if disable_correlation_request_id is not None else None
            __props__.__dict__["disable_default_output"] = pulumi.Output.from_input(disable_default_output).apply(pulumi.runtime.to_json) if disable_default_output is not None else None
            __props__.__dict__["disable_terraform_partner_id"] = pulumi.Output.from_input(disable_terraform_partner_id).apply(pulumi.runtime.to_json) if disable_terraform_partner_id is not None else None
            __props__.__dict__["enable_preflight"] = pulumi.Output.from_input(enable_preflight).apply(pulumi.runtime.to_json) if enable_preflight is not None else None
            __props__.__dict__["endpoints"] = pulumi.Output.from_input(endpoints).apply(pulumi.runtime.to_json) if endpoints is not None else None
            __props__.__dict__["environment"] = environment
            __props__.__dict__["maximum_busy_retry_attempts"] = pulumi.Output.from_input(maximum_busy_retry_attempts).apply(pulumi.runtime.to_json) if maximum_busy_retry_attempts is not None else None
            __props__.__dict__["oidc_azure_service_connection_id"] = oidc_azure_service_connection_id
            __props__.__dict__["oidc_request_token"] = oidc_request_token
            __props__.__dict__["oidc_request_url"] = oidc_request_url
            __props__.__dict__["oidc_token"] = oidc_token
            __props__.__dict__["oidc_token_file_path"] = oidc_token_file_path
            __props__.__dict__["partner_id"] = partner_id
            __props__.__dict__["skip_provider_registration"] = pulumi.Output.from_input(skip_provider_registration).apply(pulumi.runtime.to_json) if skip_provider_registration is not None else None
            __props__.__dict__["subscription_id"] = subscription_id
            __props__.__dict__["tenant_id"] = tenant_id
            __props__.__dict__["use_aks_workload_identity"] = pulumi.Output.from_input(use_aks_workload_identity).apply(pulumi.runtime.to_json) if use_aks_workload_identity is not None else None
            __props__.__dict__["use_cli"] = pulumi.Output.from_input(use_cli).apply(pulumi.runtime.to_json) if use_cli is not None else None
            __props__.__dict__["use_msi"] = pulumi.Output.from_input(use_msi).apply(pulumi.runtime.to_json) if use_msi is not None else None
            __props__.__dict__["use_oidc"] = pulumi.Output.from_input(use_oidc).apply(pulumi.runtime.to_json) if use_oidc is not None else None
        super(Provider, __self__).__init__(
            'azapi',
            resource_name,
            __props__,
            opts)

    @property
    @pulumi.getter(name="clientCertificate")
    def client_certificate(self) -> pulumi.Output[Optional[str]]:
        """
        A base64-encoded PKCS#12 bundle to be used as the client certificate for authentication. This can also be sourced from
        the `ARM_CLIENT_CERTIFICATE` environment variable.
        """
        return pulumi.get(self, "client_certificate")

    @property
    @pulumi.getter(name="clientCertificatePassword")
    def client_certificate_password(self) -> pulumi.Output[Optional[str]]:
        """
        The password associated with the Client Certificate. This can also be sourced from the `ARM_CLIENT_CERTIFICATE_PASSWORD`
        Environment Variable.
        """
        return pulumi.get(self, "client_certificate_password")

    @property
    @pulumi.getter(name="clientCertificatePath")
    def client_certificate_path(self) -> pulumi.Output[Optional[str]]:
        """
        The path to the Client Certificate associated with the Service Principal which should be used. This can also be sourced
        from the `ARM_CLIENT_CERTIFICATE_PATH` Environment Variable.
        """
        return pulumi.get(self, "client_certificate_path")

    @property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Output[Optional[str]]:
        """
        The Client ID which should be used. This can also be sourced from the `ARM_CLIENT_ID` Environment Variable.
        """
        return pulumi.get(self, "client_id")

    @property
    @pulumi.getter(name="clientIdFilePath")
    def client_id_file_path(self) -> pulumi.Output[Optional[str]]:
        """
        The path to a file containing the Client ID which should be used. This can also be sourced from the
        `ARM_CLIENT_ID_FILE_PATH` Environment Variable.
        """
        return pulumi.get(self, "client_id_file_path")

    @property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Output[Optional[str]]:
        """
        The Client Secret which should be used. This can also be sourced from the `ARM_CLIENT_SECRET` Environment Variable.
        """
        return pulumi.get(self, "client_secret")

    @property
    @pulumi.getter(name="clientSecretFilePath")
    def client_secret_file_path(self) -> pulumi.Output[Optional[str]]:
        """
        The path to a file containing the Client Secret which should be used. For use When authenticating as a Service Principal
        using a Client Secret. This can also be sourced from the `ARM_CLIENT_SECRET_FILE_PATH` Environment Variable.
        """
        return pulumi.get(self, "client_secret_file_path")

    @property
    @pulumi.getter(name="customCorrelationRequestId")
    def custom_correlation_request_id(self) -> pulumi.Output[Optional[str]]:
        """
        The value of the `x-ms-correlation-request-id` header, otherwise an auto-generated UUID will be used. This can also be
        sourced from the `ARM_CORRELATION_REQUEST_ID` environment variable.
        """
        return pulumi.get(self, "custom_correlation_request_id")

    @property
    @pulumi.getter(name="defaultLocation")
    def default_location(self) -> pulumi.Output[Optional[str]]:
        """
        The default Azure Region where the azure resource should exist. The `location` in each resource block can override the
        `default_location`. Changing this forces new resources to be created.
        """
        return pulumi.get(self, "default_location")

    @property
    @pulumi.getter(name="defaultName")
    def default_name(self) -> pulumi.Output[Optional[str]]:
        """
        The default name to create the azure resource. The `name` in each resource block can override the `default_name`.
        Changing this forces new resources to be created.
        """
        return pulumi.get(self, "default_name")

    @property
    @pulumi.getter
    def environment(self) -> pulumi.Output[Optional[str]]:
        """
        The Cloud Environment which should be used. Possible values are `public`, `usgovernment` and `china`. Defaults to
        `public`. This can also be sourced from the `ARM_ENVIRONMENT` Environment Variable.
        """
        return pulumi.get(self, "environment")

    @property
    @pulumi.getter(name="oidcAzureServiceConnectionId")
    def oidc_azure_service_connection_id(self) -> pulumi.Output[Optional[str]]:
        """
        The Azure Pipelines Service Connection ID to use for authentication. This can also be sourced from the
        `ARM_ADO_PIPELINE_SERVICE_CONNECTION_ID` or `ARM_OIDC_AZURE_SERVICE_CONNECTION_ID` Environment Variables.
        """
        return pulumi.get(self, "oidc_azure_service_connection_id")

    @property
    @pulumi.getter(name="oidcRequestToken")
    def oidc_request_token(self) -> pulumi.Output[Optional[str]]:
        """
        The bearer token for the request to the OIDC provider. This can also be sourced from the `ARM_OIDC_REQUEST_TOKEN` or
        `ACTIONS_ID_TOKEN_REQUEST_TOKEN` Environment Variables.
        """
        return pulumi.get(self, "oidc_request_token")

    @property
    @pulumi.getter(name="oidcRequestUrl")
    def oidc_request_url(self) -> pulumi.Output[Optional[str]]:
        """
        The URL for the OIDC provider from which to request an ID token. This can also be sourced from the
        `ARM_OIDC_REQUEST_URL` or `ACTIONS_ID_TOKEN_REQUEST_URL` Environment Variables.
        """
        return pulumi.get(self, "oidc_request_url")

    @property
    @pulumi.getter(name="oidcToken")
    def oidc_token(self) -> pulumi.Output[Optional[str]]:
        """
        The ID token when authenticating using OpenID Connect (OIDC). This can also be sourced from the `ARM_OIDC_TOKEN`
        environment Variable.
        """
        return pulumi.get(self, "oidc_token")

    @property
    @pulumi.getter(name="oidcTokenFilePath")
    def oidc_token_file_path(self) -> pulumi.Output[Optional[str]]:
        """
        The path to a file containing an ID token when authenticating using OpenID Connect (OIDC). This can also be sourced from
        the `ARM_OIDC_TOKEN_FILE_PATH` environment Variable.
        """
        return pulumi.get(self, "oidc_token_file_path")

    @property
    @pulumi.getter(name="partnerId")
    def partner_id(self) -> pulumi.Output[Optional[str]]:
        """
        A GUID/UUID that is
        [registered](https://docs.microsoft.com/azure/marketplace/azure-partner-customer-usage-attribution#register-guids-and-offers)
        with Microsoft to facilitate partner resource usage attribution. This can also be sourced from the `ARM_PARTNER_ID`
        Environment Variable.
        """
        return pulumi.get(self, "partner_id")

    @property
    @pulumi.getter(name="subscriptionId")
    def subscription_id(self) -> pulumi.Output[Optional[str]]:
        """
        The Subscription ID which should be used. This can also be sourced from the `ARM_SUBSCRIPTION_ID` Environment Variable.
        """
        return pulumi.get(self, "subscription_id")

    @property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> pulumi.Output[Optional[str]]:
        """
        The Tenant ID should be used. This can also be sourced from the `ARM_TENANT_ID` Environment Variable.
        """
        return pulumi.get(self, "tenant_id")

