# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ResourceActionArgs', 'ResourceAction']

@pulumi.input_type
class ResourceActionArgs:
    def __init__(__self__, *,
                 resource_id: pulumi.Input[str],
                 type: pulumi.Input[str],
                 action: Optional[pulumi.Input[str]] = None,
                 body: Optional[Any] = None,
                 headers: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 locks: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 method: Optional[pulumi.Input[str]] = None,
                 query_parameters: Optional[pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[str]]]]]] = None,
                 response_export_values: Optional[Any] = None,
                 retry: Optional[pulumi.Input['ResourceActionRetryArgs']] = None,
                 sensitive_response_export_values: Optional[Any] = None,
                 timeouts: Optional[pulumi.Input['ResourceActionTimeoutsArgs']] = None,
                 when: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a ResourceAction resource.
        :param pulumi.Input[str] resource_id: The ID of an existing Azure source.
        :param pulumi.Input[str] type: In a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example,
               `Microsoft.Storage/storageAccounts`. `<api-version>` is version of the API used to manage this azure resource.
        :param pulumi.Input[str] action: The name of the resource action. It's also possible to make HTTP requests towards the resource ID if leave this field
               empty.
        :param Any body: A dynamic attribute that contains the request body.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] headers: A map of headers to include in the request
        :param pulumi.Input[Sequence[pulumi.Input[str]]] locks: A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
        :param pulumi.Input[str] method: Specifies the HTTP method of the azure resource action. Allowed values are `POST`, `PATCH`, `PUT` and `DELETE`. Defaults
               to `POST`.
        :param pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[str]]]]] query_parameters: A map of query parameters to include in the request
        :param Any response_export_values: The attribute can accept either a list or a map. - **List**: A list of paths that need to be exported from the response
               body. Setting it to `["*"]` will export the full response body. Here's an example. If it sets to
               `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to the
               computed property output. ```text { properties = { loginServer = "registry1.azurecr.io" policies = { quarantinePolicy =
               { status = "disabled" } } } } ``` - **Map**: A map where the key is the name for the result and the value is a JMESPath
               query string to filter the response. Here's an example. If it sets to `{"login_server": "properties.loginServer",
               "quarantine_status": "properties.policies.quarantinePolicy.status"}`, it will set the following HCL object to the
               computed property output. ```text { "login_server" = "registry1.azurecr.io" "quarantine_status" = "disabled" } ``` To
               learn more about JMESPath, visit [JMESPath](https://jmespath.org/).
        :param pulumi.Input['ResourceActionRetryArgs'] retry: The retry object supports the following attributes:
        :param Any sensitive_response_export_values: The attribute can accept either a list or a map. - **List**: A list of paths that need to be exported from the response
               body. Setting it to `["*"]` will export the full response body. Here's an example. If it sets to
               `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to the
               computed property output. ```text { properties = { loginServer = "registry1.azurecr.io" policies = { quarantinePolicy =
               { status = "disabled" } } } } ``` - **Map**: A map where the key is the name for the result and the value is a JMESPath
               query string to filter the response. Here's an example. If it sets to `{"login_server": "properties.loginServer",
               "quarantine_status": "properties.policies.quarantinePolicy.status"}`, it will set the following HCL object to the
               computed property output. ```text { "login_server" = "registry1.azurecr.io" "quarantine_status" = "disabled" } ``` To
               learn more about JMESPath, visit [JMESPath](https://jmespath.org/).
        :param pulumi.Input[str] when: When to perform the action, value must be one of: `apply`, `destroy`. Default is `apply`.
        """
        pulumi.set(__self__, "resource_id", resource_id)
        pulumi.set(__self__, "type", type)
        if action is not None:
            pulumi.set(__self__, "action", action)
        if body is not None:
            pulumi.set(__self__, "body", body)
        if headers is not None:
            pulumi.set(__self__, "headers", headers)
        if locks is not None:
            pulumi.set(__self__, "locks", locks)
        if method is not None:
            pulumi.set(__self__, "method", method)
        if query_parameters is not None:
            pulumi.set(__self__, "query_parameters", query_parameters)
        if response_export_values is not None:
            pulumi.set(__self__, "response_export_values", response_export_values)
        if retry is not None:
            pulumi.set(__self__, "retry", retry)
        if sensitive_response_export_values is not None:
            pulumi.set(__self__, "sensitive_response_export_values", sensitive_response_export_values)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)
        if when is not None:
            pulumi.set(__self__, "when", when)

    @property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> pulumi.Input[str]:
        """
        The ID of an existing Azure source.
        """
        return pulumi.get(self, "resource_id")

    @resource_id.setter
    def resource_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "resource_id", value)

    @property
    @pulumi.getter
    def type(self) -> pulumi.Input[str]:
        """
        In a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example,
        `Microsoft.Storage/storageAccounts`. `<api-version>` is version of the API used to manage this azure resource.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[str]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter
    def action(self) -> Optional[pulumi.Input[str]]:
        """
        The name of the resource action. It's also possible to make HTTP requests towards the resource ID if leave this field
        empty.
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "action", value)

    @property
    @pulumi.getter
    def body(self) -> Optional[Any]:
        """
        A dynamic attribute that contains the request body.
        """
        return pulumi.get(self, "body")

    @body.setter
    def body(self, value: Optional[Any]):
        pulumi.set(self, "body", value)

    @property
    @pulumi.getter
    def headers(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        A map of headers to include in the request
        """
        return pulumi.get(self, "headers")

    @headers.setter
    def headers(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "headers", value)

    @property
    @pulumi.getter
    def locks(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
        """
        return pulumi.get(self, "locks")

    @locks.setter
    def locks(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "locks", value)

    @property
    @pulumi.getter
    def method(self) -> Optional[pulumi.Input[str]]:
        """
        Specifies the HTTP method of the azure resource action. Allowed values are `POST`, `PATCH`, `PUT` and `DELETE`. Defaults
        to `POST`.
        """
        return pulumi.get(self, "method")

    @method.setter
    def method(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "method", value)

    @property
    @pulumi.getter(name="queryParameters")
    def query_parameters(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[str]]]]]]:
        """
        A map of query parameters to include in the request
        """
        return pulumi.get(self, "query_parameters")

    @query_parameters.setter
    def query_parameters(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[str]]]]]]):
        pulumi.set(self, "query_parameters", value)

    @property
    @pulumi.getter(name="responseExportValues")
    def response_export_values(self) -> Optional[Any]:
        """
        The attribute can accept either a list or a map. - **List**: A list of paths that need to be exported from the response
        body. Setting it to `["*"]` will export the full response body. Here's an example. If it sets to
        `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to the
        computed property output. ```text { properties = { loginServer = "registry1.azurecr.io" policies = { quarantinePolicy =
        { status = "disabled" } } } } ``` - **Map**: A map where the key is the name for the result and the value is a JMESPath
        query string to filter the response. Here's an example. If it sets to `{"login_server": "properties.loginServer",
        "quarantine_status": "properties.policies.quarantinePolicy.status"}`, it will set the following HCL object to the
        computed property output. ```text { "login_server" = "registry1.azurecr.io" "quarantine_status" = "disabled" } ``` To
        learn more about JMESPath, visit [JMESPath](https://jmespath.org/).
        """
        return pulumi.get(self, "response_export_values")

    @response_export_values.setter
    def response_export_values(self, value: Optional[Any]):
        pulumi.set(self, "response_export_values", value)

    @property
    @pulumi.getter
    def retry(self) -> Optional[pulumi.Input['ResourceActionRetryArgs']]:
        """
        The retry object supports the following attributes:
        """
        return pulumi.get(self, "retry")

    @retry.setter
    def retry(self, value: Optional[pulumi.Input['ResourceActionRetryArgs']]):
        pulumi.set(self, "retry", value)

    @property
    @pulumi.getter(name="sensitiveResponseExportValues")
    def sensitive_response_export_values(self) -> Optional[Any]:
        """
        The attribute can accept either a list or a map. - **List**: A list of paths that need to be exported from the response
        body. Setting it to `["*"]` will export the full response body. Here's an example. If it sets to
        `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to the
        computed property output. ```text { properties = { loginServer = "registry1.azurecr.io" policies = { quarantinePolicy =
        { status = "disabled" } } } } ``` - **Map**: A map where the key is the name for the result and the value is a JMESPath
        query string to filter the response. Here's an example. If it sets to `{"login_server": "properties.loginServer",
        "quarantine_status": "properties.policies.quarantinePolicy.status"}`, it will set the following HCL object to the
        computed property output. ```text { "login_server" = "registry1.azurecr.io" "quarantine_status" = "disabled" } ``` To
        learn more about JMESPath, visit [JMESPath](https://jmespath.org/).
        """
        return pulumi.get(self, "sensitive_response_export_values")

    @sensitive_response_export_values.setter
    def sensitive_response_export_values(self, value: Optional[Any]):
        pulumi.set(self, "sensitive_response_export_values", value)

    @property
    @pulumi.getter
    def timeouts(self) -> Optional[pulumi.Input['ResourceActionTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: Optional[pulumi.Input['ResourceActionTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)

    @property
    @pulumi.getter
    def when(self) -> Optional[pulumi.Input[str]]:
        """
        When to perform the action, value must be one of: `apply`, `destroy`. Default is `apply`.
        """
        return pulumi.get(self, "when")

    @when.setter
    def when(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "when", value)


@pulumi.input_type
class _ResourceActionState:
    def __init__(__self__, *,
                 action: Optional[pulumi.Input[str]] = None,
                 body: Optional[Any] = None,
                 headers: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 locks: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 method: Optional[pulumi.Input[str]] = None,
                 output: Optional[Any] = None,
                 query_parameters: Optional[pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[str]]]]]] = None,
                 resource_id: Optional[pulumi.Input[str]] = None,
                 response_export_values: Optional[Any] = None,
                 retry: Optional[pulumi.Input['ResourceActionRetryArgs']] = None,
                 sensitive_output: Optional[Any] = None,
                 sensitive_response_export_values: Optional[Any] = None,
                 timeouts: Optional[pulumi.Input['ResourceActionTimeoutsArgs']] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 when: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering ResourceAction resources.
        :param pulumi.Input[str] action: The name of the resource action. It's also possible to make HTTP requests towards the resource ID if leave this field
               empty.
        :param Any body: A dynamic attribute that contains the request body.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] headers: A map of headers to include in the request
        :param pulumi.Input[Sequence[pulumi.Input[str]]] locks: A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
        :param pulumi.Input[str] method: Specifies the HTTP method of the azure resource action. Allowed values are `POST`, `PATCH`, `PUT` and `DELETE`. Defaults
               to `POST`.
        :param Any output: The output HCL object containing the properties specified in `response_export_values`. Here are some examples to use the
               values. ```terraform // it will output "registry1.azurecr.io" output "login_server" { value =
               azapi_resource_action.example.output.properties.loginServer } // it will output "disabled" output "quarantine_policy" {
               value = azapi_resource_action.example.output.properties.policies.quarantinePolicy.status } ```
        :param pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[str]]]]] query_parameters: A map of query parameters to include in the request
        :param pulumi.Input[str] resource_id: The ID of an existing Azure source.
        :param Any response_export_values: The attribute can accept either a list or a map. - **List**: A list of paths that need to be exported from the response
               body. Setting it to `["*"]` will export the full response body. Here's an example. If it sets to
               `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to the
               computed property output. ```text { properties = { loginServer = "registry1.azurecr.io" policies = { quarantinePolicy =
               { status = "disabled" } } } } ``` - **Map**: A map where the key is the name for the result and the value is a JMESPath
               query string to filter the response. Here's an example. If it sets to `{"login_server": "properties.loginServer",
               "quarantine_status": "properties.policies.quarantinePolicy.status"}`, it will set the following HCL object to the
               computed property output. ```text { "login_server" = "registry1.azurecr.io" "quarantine_status" = "disabled" } ``` To
               learn more about JMESPath, visit [JMESPath](https://jmespath.org/).
        :param pulumi.Input['ResourceActionRetryArgs'] retry: The retry object supports the following attributes:
        :param Any sensitive_output: The output HCL object containing the properties specified in `sensitive_response_export_values`. Here are some examples
               to use the values. ```terraform // it will output "registry1.azurecr.io" output "login_server" { value =
               azapi_resource_action.example.sensitive_output.properties.loginServer sensitive = true } // it will output "disabled"
               output "quarantine_policy" { value =
               azapi_resource_action.example.sensitive_output.properties.policies.quarantinePolicy.status sensitive = true } ```
        :param Any sensitive_response_export_values: The attribute can accept either a list or a map. - **List**: A list of paths that need to be exported from the response
               body. Setting it to `["*"]` will export the full response body. Here's an example. If it sets to
               `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to the
               computed property output. ```text { properties = { loginServer = "registry1.azurecr.io" policies = { quarantinePolicy =
               { status = "disabled" } } } } ``` - **Map**: A map where the key is the name for the result and the value is a JMESPath
               query string to filter the response. Here's an example. If it sets to `{"login_server": "properties.loginServer",
               "quarantine_status": "properties.policies.quarantinePolicy.status"}`, it will set the following HCL object to the
               computed property output. ```text { "login_server" = "registry1.azurecr.io" "quarantine_status" = "disabled" } ``` To
               learn more about JMESPath, visit [JMESPath](https://jmespath.org/).
        :param pulumi.Input[str] type: In a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example,
               `Microsoft.Storage/storageAccounts`. `<api-version>` is version of the API used to manage this azure resource.
        :param pulumi.Input[str] when: When to perform the action, value must be one of: `apply`, `destroy`. Default is `apply`.
        """
        if action is not None:
            pulumi.set(__self__, "action", action)
        if body is not None:
            pulumi.set(__self__, "body", body)
        if headers is not None:
            pulumi.set(__self__, "headers", headers)
        if locks is not None:
            pulumi.set(__self__, "locks", locks)
        if method is not None:
            pulumi.set(__self__, "method", method)
        if output is not None:
            pulumi.set(__self__, "output", output)
        if query_parameters is not None:
            pulumi.set(__self__, "query_parameters", query_parameters)
        if resource_id is not None:
            pulumi.set(__self__, "resource_id", resource_id)
        if response_export_values is not None:
            pulumi.set(__self__, "response_export_values", response_export_values)
        if retry is not None:
            pulumi.set(__self__, "retry", retry)
        if sensitive_output is not None:
            pulumi.set(__self__, "sensitive_output", sensitive_output)
        if sensitive_response_export_values is not None:
            pulumi.set(__self__, "sensitive_response_export_values", sensitive_response_export_values)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if when is not None:
            pulumi.set(__self__, "when", when)

    @property
    @pulumi.getter
    def action(self) -> Optional[pulumi.Input[str]]:
        """
        The name of the resource action. It's also possible to make HTTP requests towards the resource ID if leave this field
        empty.
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "action", value)

    @property
    @pulumi.getter
    def body(self) -> Optional[Any]:
        """
        A dynamic attribute that contains the request body.
        """
        return pulumi.get(self, "body")

    @body.setter
    def body(self, value: Optional[Any]):
        pulumi.set(self, "body", value)

    @property
    @pulumi.getter
    def headers(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        A map of headers to include in the request
        """
        return pulumi.get(self, "headers")

    @headers.setter
    def headers(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "headers", value)

    @property
    @pulumi.getter
    def locks(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
        """
        return pulumi.get(self, "locks")

    @locks.setter
    def locks(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "locks", value)

    @property
    @pulumi.getter
    def method(self) -> Optional[pulumi.Input[str]]:
        """
        Specifies the HTTP method of the azure resource action. Allowed values are `POST`, `PATCH`, `PUT` and `DELETE`. Defaults
        to `POST`.
        """
        return pulumi.get(self, "method")

    @method.setter
    def method(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "method", value)

    @property
    @pulumi.getter
    def output(self) -> Optional[Any]:
        """
        The output HCL object containing the properties specified in `response_export_values`. Here are some examples to use the
        values. ```terraform // it will output "registry1.azurecr.io" output "login_server" { value =
        azapi_resource_action.example.output.properties.loginServer } // it will output "disabled" output "quarantine_policy" {
        value = azapi_resource_action.example.output.properties.policies.quarantinePolicy.status } ```
        """
        return pulumi.get(self, "output")

    @output.setter
    def output(self, value: Optional[Any]):
        pulumi.set(self, "output", value)

    @property
    @pulumi.getter(name="queryParameters")
    def query_parameters(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[str]]]]]]:
        """
        A map of query parameters to include in the request
        """
        return pulumi.get(self, "query_parameters")

    @query_parameters.setter
    def query_parameters(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[str]]]]]]):
        pulumi.set(self, "query_parameters", value)

    @property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> Optional[pulumi.Input[str]]:
        """
        The ID of an existing Azure source.
        """
        return pulumi.get(self, "resource_id")

    @resource_id.setter
    def resource_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "resource_id", value)

    @property
    @pulumi.getter(name="responseExportValues")
    def response_export_values(self) -> Optional[Any]:
        """
        The attribute can accept either a list or a map. - **List**: A list of paths that need to be exported from the response
        body. Setting it to `["*"]` will export the full response body. Here's an example. If it sets to
        `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to the
        computed property output. ```text { properties = { loginServer = "registry1.azurecr.io" policies = { quarantinePolicy =
        { status = "disabled" } } } } ``` - **Map**: A map where the key is the name for the result and the value is a JMESPath
        query string to filter the response. Here's an example. If it sets to `{"login_server": "properties.loginServer",
        "quarantine_status": "properties.policies.quarantinePolicy.status"}`, it will set the following HCL object to the
        computed property output. ```text { "login_server" = "registry1.azurecr.io" "quarantine_status" = "disabled" } ``` To
        learn more about JMESPath, visit [JMESPath](https://jmespath.org/).
        """
        return pulumi.get(self, "response_export_values")

    @response_export_values.setter
    def response_export_values(self, value: Optional[Any]):
        pulumi.set(self, "response_export_values", value)

    @property
    @pulumi.getter
    def retry(self) -> Optional[pulumi.Input['ResourceActionRetryArgs']]:
        """
        The retry object supports the following attributes:
        """
        return pulumi.get(self, "retry")

    @retry.setter
    def retry(self, value: Optional[pulumi.Input['ResourceActionRetryArgs']]):
        pulumi.set(self, "retry", value)

    @property
    @pulumi.getter(name="sensitiveOutput")
    def sensitive_output(self) -> Optional[Any]:
        """
        The output HCL object containing the properties specified in `sensitive_response_export_values`. Here are some examples
        to use the values. ```terraform // it will output "registry1.azurecr.io" output "login_server" { value =
        azapi_resource_action.example.sensitive_output.properties.loginServer sensitive = true } // it will output "disabled"
        output "quarantine_policy" { value =
        azapi_resource_action.example.sensitive_output.properties.policies.quarantinePolicy.status sensitive = true } ```
        """
        return pulumi.get(self, "sensitive_output")

    @sensitive_output.setter
    def sensitive_output(self, value: Optional[Any]):
        pulumi.set(self, "sensitive_output", value)

    @property
    @pulumi.getter(name="sensitiveResponseExportValues")
    def sensitive_response_export_values(self) -> Optional[Any]:
        """
        The attribute can accept either a list or a map. - **List**: A list of paths that need to be exported from the response
        body. Setting it to `["*"]` will export the full response body. Here's an example. If it sets to
        `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to the
        computed property output. ```text { properties = { loginServer = "registry1.azurecr.io" policies = { quarantinePolicy =
        { status = "disabled" } } } } ``` - **Map**: A map where the key is the name for the result and the value is a JMESPath
        query string to filter the response. Here's an example. If it sets to `{"login_server": "properties.loginServer",
        "quarantine_status": "properties.policies.quarantinePolicy.status"}`, it will set the following HCL object to the
        computed property output. ```text { "login_server" = "registry1.azurecr.io" "quarantine_status" = "disabled" } ``` To
        learn more about JMESPath, visit [JMESPath](https://jmespath.org/).
        """
        return pulumi.get(self, "sensitive_response_export_values")

    @sensitive_response_export_values.setter
    def sensitive_response_export_values(self, value: Optional[Any]):
        pulumi.set(self, "sensitive_response_export_values", value)

    @property
    @pulumi.getter
    def timeouts(self) -> Optional[pulumi.Input['ResourceActionTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: Optional[pulumi.Input['ResourceActionTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)

    @property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[str]]:
        """
        In a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example,
        `Microsoft.Storage/storageAccounts`. `<api-version>` is version of the API used to manage this azure resource.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter
    def when(self) -> Optional[pulumi.Input[str]]:
        """
        When to perform the action, value must be one of: `apply`, `destroy`. Default is `apply`.
        """
        return pulumi.get(self, "when")

    @when.setter
    def when(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "when", value)


class ResourceAction(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 action: Optional[pulumi.Input[str]] = None,
                 body: Optional[Any] = None,
                 headers: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 locks: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 method: Optional[pulumi.Input[str]] = None,
                 query_parameters: Optional[pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[str]]]]]] = None,
                 resource_id: Optional[pulumi.Input[str]] = None,
                 response_export_values: Optional[Any] = None,
                 retry: Optional[pulumi.Input[Union['ResourceActionRetryArgs', 'ResourceActionRetryArgsDict']]] = None,
                 sensitive_response_export_values: Optional[Any] = None,
                 timeouts: Optional[pulumi.Input[Union['ResourceActionTimeoutsArgs', 'ResourceActionTimeoutsArgsDict']]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 when: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        ## Example Usage

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] action: The name of the resource action. It's also possible to make HTTP requests towards the resource ID if leave this field
               empty.
        :param Any body: A dynamic attribute that contains the request body.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] headers: A map of headers to include in the request
        :param pulumi.Input[Sequence[pulumi.Input[str]]] locks: A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
        :param pulumi.Input[str] method: Specifies the HTTP method of the azure resource action. Allowed values are `POST`, `PATCH`, `PUT` and `DELETE`. Defaults
               to `POST`.
        :param pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[str]]]]] query_parameters: A map of query parameters to include in the request
        :param pulumi.Input[str] resource_id: The ID of an existing Azure source.
        :param Any response_export_values: The attribute can accept either a list or a map. - **List**: A list of paths that need to be exported from the response
               body. Setting it to `["*"]` will export the full response body. Here's an example. If it sets to
               `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to the
               computed property output. ```text { properties = { loginServer = "registry1.azurecr.io" policies = { quarantinePolicy =
               { status = "disabled" } } } } ``` - **Map**: A map where the key is the name for the result and the value is a JMESPath
               query string to filter the response. Here's an example. If it sets to `{"login_server": "properties.loginServer",
               "quarantine_status": "properties.policies.quarantinePolicy.status"}`, it will set the following HCL object to the
               computed property output. ```text { "login_server" = "registry1.azurecr.io" "quarantine_status" = "disabled" } ``` To
               learn more about JMESPath, visit [JMESPath](https://jmespath.org/).
        :param pulumi.Input[Union['ResourceActionRetryArgs', 'ResourceActionRetryArgsDict']] retry: The retry object supports the following attributes:
        :param Any sensitive_response_export_values: The attribute can accept either a list or a map. - **List**: A list of paths that need to be exported from the response
               body. Setting it to `["*"]` will export the full response body. Here's an example. If it sets to
               `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to the
               computed property output. ```text { properties = { loginServer = "registry1.azurecr.io" policies = { quarantinePolicy =
               { status = "disabled" } } } } ``` - **Map**: A map where the key is the name for the result and the value is a JMESPath
               query string to filter the response. Here's an example. If it sets to `{"login_server": "properties.loginServer",
               "quarantine_status": "properties.policies.quarantinePolicy.status"}`, it will set the following HCL object to the
               computed property output. ```text { "login_server" = "registry1.azurecr.io" "quarantine_status" = "disabled" } ``` To
               learn more about JMESPath, visit [JMESPath](https://jmespath.org/).
        :param pulumi.Input[str] type: In a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example,
               `Microsoft.Storage/storageAccounts`. `<api-version>` is version of the API used to manage this azure resource.
        :param pulumi.Input[str] when: When to perform the action, value must be one of: `apply`, `destroy`. Default is `apply`.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ResourceActionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## Example Usage

        :param str resource_name: The name of the resource.
        :param ResourceActionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ResourceActionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 action: Optional[pulumi.Input[str]] = None,
                 body: Optional[Any] = None,
                 headers: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 locks: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 method: Optional[pulumi.Input[str]] = None,
                 query_parameters: Optional[pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[str]]]]]] = None,
                 resource_id: Optional[pulumi.Input[str]] = None,
                 response_export_values: Optional[Any] = None,
                 retry: Optional[pulumi.Input[Union['ResourceActionRetryArgs', 'ResourceActionRetryArgsDict']]] = None,
                 sensitive_response_export_values: Optional[Any] = None,
                 timeouts: Optional[pulumi.Input[Union['ResourceActionTimeoutsArgs', 'ResourceActionTimeoutsArgsDict']]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 when: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ResourceActionArgs.__new__(ResourceActionArgs)

            __props__.__dict__["action"] = action
            __props__.__dict__["body"] = body
            __props__.__dict__["headers"] = headers
            __props__.__dict__["locks"] = locks
            __props__.__dict__["method"] = method
            __props__.__dict__["query_parameters"] = query_parameters
            if resource_id is None and not opts.urn:
                raise TypeError("Missing required property 'resource_id'")
            __props__.__dict__["resource_id"] = resource_id
            __props__.__dict__["response_export_values"] = response_export_values
            __props__.__dict__["retry"] = retry
            __props__.__dict__["sensitive_response_export_values"] = sensitive_response_export_values
            __props__.__dict__["timeouts"] = timeouts
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
            __props__.__dict__["when"] = when
            __props__.__dict__["output"] = None
            __props__.__dict__["sensitive_output"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["sensitiveOutput"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ResourceAction, __self__).__init__(
            'azapi:index/resourceAction:ResourceAction',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            action: Optional[pulumi.Input[str]] = None,
            body: Optional[Any] = None,
            headers: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
            locks: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
            method: Optional[pulumi.Input[str]] = None,
            output: Optional[Any] = None,
            query_parameters: Optional[pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[str]]]]]] = None,
            resource_id: Optional[pulumi.Input[str]] = None,
            response_export_values: Optional[Any] = None,
            retry: Optional[pulumi.Input[Union['ResourceActionRetryArgs', 'ResourceActionRetryArgsDict']]] = None,
            sensitive_output: Optional[Any] = None,
            sensitive_response_export_values: Optional[Any] = None,
            timeouts: Optional[pulumi.Input[Union['ResourceActionTimeoutsArgs', 'ResourceActionTimeoutsArgsDict']]] = None,
            type: Optional[pulumi.Input[str]] = None,
            when: Optional[pulumi.Input[str]] = None) -> 'ResourceAction':
        """
        Get an existing ResourceAction resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] action: The name of the resource action. It's also possible to make HTTP requests towards the resource ID if leave this field
               empty.
        :param Any body: A dynamic attribute that contains the request body.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] headers: A map of headers to include in the request
        :param pulumi.Input[Sequence[pulumi.Input[str]]] locks: A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
        :param pulumi.Input[str] method: Specifies the HTTP method of the azure resource action. Allowed values are `POST`, `PATCH`, `PUT` and `DELETE`. Defaults
               to `POST`.
        :param Any output: The output HCL object containing the properties specified in `response_export_values`. Here are some examples to use the
               values. ```terraform // it will output "registry1.azurecr.io" output "login_server" { value =
               azapi_resource_action.example.output.properties.loginServer } // it will output "disabled" output "quarantine_policy" {
               value = azapi_resource_action.example.output.properties.policies.quarantinePolicy.status } ```
        :param pulumi.Input[Mapping[str, pulumi.Input[Sequence[pulumi.Input[str]]]]] query_parameters: A map of query parameters to include in the request
        :param pulumi.Input[str] resource_id: The ID of an existing Azure source.
        :param Any response_export_values: The attribute can accept either a list or a map. - **List**: A list of paths that need to be exported from the response
               body. Setting it to `["*"]` will export the full response body. Here's an example. If it sets to
               `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to the
               computed property output. ```text { properties = { loginServer = "registry1.azurecr.io" policies = { quarantinePolicy =
               { status = "disabled" } } } } ``` - **Map**: A map where the key is the name for the result and the value is a JMESPath
               query string to filter the response. Here's an example. If it sets to `{"login_server": "properties.loginServer",
               "quarantine_status": "properties.policies.quarantinePolicy.status"}`, it will set the following HCL object to the
               computed property output. ```text { "login_server" = "registry1.azurecr.io" "quarantine_status" = "disabled" } ``` To
               learn more about JMESPath, visit [JMESPath](https://jmespath.org/).
        :param pulumi.Input[Union['ResourceActionRetryArgs', 'ResourceActionRetryArgsDict']] retry: The retry object supports the following attributes:
        :param Any sensitive_output: The output HCL object containing the properties specified in `sensitive_response_export_values`. Here are some examples
               to use the values. ```terraform // it will output "registry1.azurecr.io" output "login_server" { value =
               azapi_resource_action.example.sensitive_output.properties.loginServer sensitive = true } // it will output "disabled"
               output "quarantine_policy" { value =
               azapi_resource_action.example.sensitive_output.properties.policies.quarantinePolicy.status sensitive = true } ```
        :param Any sensitive_response_export_values: The attribute can accept either a list or a map. - **List**: A list of paths that need to be exported from the response
               body. Setting it to `["*"]` will export the full response body. Here's an example. If it sets to
               `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to the
               computed property output. ```text { properties = { loginServer = "registry1.azurecr.io" policies = { quarantinePolicy =
               { status = "disabled" } } } } ``` - **Map**: A map where the key is the name for the result and the value is a JMESPath
               query string to filter the response. Here's an example. If it sets to `{"login_server": "properties.loginServer",
               "quarantine_status": "properties.policies.quarantinePolicy.status"}`, it will set the following HCL object to the
               computed property output. ```text { "login_server" = "registry1.azurecr.io" "quarantine_status" = "disabled" } ``` To
               learn more about JMESPath, visit [JMESPath](https://jmespath.org/).
        :param pulumi.Input[str] type: In a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example,
               `Microsoft.Storage/storageAccounts`. `<api-version>` is version of the API used to manage this azure resource.
        :param pulumi.Input[str] when: When to perform the action, value must be one of: `apply`, `destroy`. Default is `apply`.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ResourceActionState.__new__(_ResourceActionState)

        __props__.__dict__["action"] = action
        __props__.__dict__["body"] = body
        __props__.__dict__["headers"] = headers
        __props__.__dict__["locks"] = locks
        __props__.__dict__["method"] = method
        __props__.__dict__["output"] = output
        __props__.__dict__["query_parameters"] = query_parameters
        __props__.__dict__["resource_id"] = resource_id
        __props__.__dict__["response_export_values"] = response_export_values
        __props__.__dict__["retry"] = retry
        __props__.__dict__["sensitive_output"] = sensitive_output
        __props__.__dict__["sensitive_response_export_values"] = sensitive_response_export_values
        __props__.__dict__["timeouts"] = timeouts
        __props__.__dict__["type"] = type
        __props__.__dict__["when"] = when
        return ResourceAction(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def action(self) -> pulumi.Output[Optional[str]]:
        """
        The name of the resource action. It's also possible to make HTTP requests towards the resource ID if leave this field
        empty.
        """
        return pulumi.get(self, "action")

    @property
    @pulumi.getter
    def body(self) -> pulumi.Output[Optional[Any]]:
        """
        A dynamic attribute that contains the request body.
        """
        return pulumi.get(self, "body")

    @property
    @pulumi.getter
    def headers(self) -> pulumi.Output[Optional[Mapping[str, str]]]:
        """
        A map of headers to include in the request
        """
        return pulumi.get(self, "headers")

    @property
    @pulumi.getter
    def locks(self) -> pulumi.Output[Optional[Sequence[str]]]:
        """
        A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
        """
        return pulumi.get(self, "locks")

    @property
    @pulumi.getter
    def method(self) -> pulumi.Output[str]:
        """
        Specifies the HTTP method of the azure resource action. Allowed values are `POST`, `PATCH`, `PUT` and `DELETE`. Defaults
        to `POST`.
        """
        return pulumi.get(self, "method")

    @property
    @pulumi.getter
    def output(self) -> pulumi.Output[Any]:
        """
        The output HCL object containing the properties specified in `response_export_values`. Here are some examples to use the
        values. ```terraform // it will output "registry1.azurecr.io" output "login_server" { value =
        azapi_resource_action.example.output.properties.loginServer } // it will output "disabled" output "quarantine_policy" {
        value = azapi_resource_action.example.output.properties.policies.quarantinePolicy.status } ```
        """
        return pulumi.get(self, "output")

    @property
    @pulumi.getter(name="queryParameters")
    def query_parameters(self) -> pulumi.Output[Optional[Mapping[str, Sequence[str]]]]:
        """
        A map of query parameters to include in the request
        """
        return pulumi.get(self, "query_parameters")

    @property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> pulumi.Output[str]:
        """
        The ID of an existing Azure source.
        """
        return pulumi.get(self, "resource_id")

    @property
    @pulumi.getter(name="responseExportValues")
    def response_export_values(self) -> pulumi.Output[Optional[Any]]:
        """
        The attribute can accept either a list or a map. - **List**: A list of paths that need to be exported from the response
        body. Setting it to `["*"]` will export the full response body. Here's an example. If it sets to
        `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to the
        computed property output. ```text { properties = { loginServer = "registry1.azurecr.io" policies = { quarantinePolicy =
        { status = "disabled" } } } } ``` - **Map**: A map where the key is the name for the result and the value is a JMESPath
        query string to filter the response. Here's an example. If it sets to `{"login_server": "properties.loginServer",
        "quarantine_status": "properties.policies.quarantinePolicy.status"}`, it will set the following HCL object to the
        computed property output. ```text { "login_server" = "registry1.azurecr.io" "quarantine_status" = "disabled" } ``` To
        learn more about JMESPath, visit [JMESPath](https://jmespath.org/).
        """
        return pulumi.get(self, "response_export_values")

    @property
    @pulumi.getter
    def retry(self) -> pulumi.Output[Optional['outputs.ResourceActionRetry']]:
        """
        The retry object supports the following attributes:
        """
        return pulumi.get(self, "retry")

    @property
    @pulumi.getter(name="sensitiveOutput")
    def sensitive_output(self) -> pulumi.Output[Any]:
        """
        The output HCL object containing the properties specified in `sensitive_response_export_values`. Here are some examples
        to use the values. ```terraform // it will output "registry1.azurecr.io" output "login_server" { value =
        azapi_resource_action.example.sensitive_output.properties.loginServer sensitive = true } // it will output "disabled"
        output "quarantine_policy" { value =
        azapi_resource_action.example.sensitive_output.properties.policies.quarantinePolicy.status sensitive = true } ```
        """
        return pulumi.get(self, "sensitive_output")

    @property
    @pulumi.getter(name="sensitiveResponseExportValues")
    def sensitive_response_export_values(self) -> pulumi.Output[Optional[Any]]:
        """
        The attribute can accept either a list or a map. - **List**: A list of paths that need to be exported from the response
        body. Setting it to `["*"]` will export the full response body. Here's an example. If it sets to
        `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following HCL object to the
        computed property output. ```text { properties = { loginServer = "registry1.azurecr.io" policies = { quarantinePolicy =
        { status = "disabled" } } } } ``` - **Map**: A map where the key is the name for the result and the value is a JMESPath
        query string to filter the response. Here's an example. If it sets to `{"login_server": "properties.loginServer",
        "quarantine_status": "properties.policies.quarantinePolicy.status"}`, it will set the following HCL object to the
        computed property output. ```text { "login_server" = "registry1.azurecr.io" "quarantine_status" = "disabled" } ``` To
        learn more about JMESPath, visit [JMESPath](https://jmespath.org/).
        """
        return pulumi.get(self, "sensitive_response_export_values")

    @property
    @pulumi.getter
    def timeouts(self) -> pulumi.Output[Optional['outputs.ResourceActionTimeouts']]:
        return pulumi.get(self, "timeouts")

    @property
    @pulumi.getter
    def type(self) -> pulumi.Output[str]:
        """
        In a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example,
        `Microsoft.Storage/storageAccounts`. `<api-version>` is version of the API used to manage this azure resource.
        """
        return pulumi.get(self, "type")

    @property
    @pulumi.getter
    def when(self) -> pulumi.Output[str]:
        """
        When to perform the action, value must be one of: `apply`, `destroy`. Default is `apply`.
        """
        return pulumi.get(self, "when")

