// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as azapi from "@pulumi/azapi";
 *
 * const account = azapi.getResourceId({
 *     type: "Microsoft.Automation/automationAccounts@2021-06-22",
 *     resourceId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1/providers/Microsoft.Automation/automationAccounts/automationAccount1",
 * });
 * export const accountName = account.then(account => account.name);
 * export const accountResourceGroup = account.then(account => account.resourceGroupName);
 * export const accountSubscription = account.then(account => account.subscriptionId);
 * export const accountParentId = account.then(account => account.parentId);
 * const vnet = azapi.getResourceId({
 *     type: "Microsoft.Network/virtualNetworks@2021-02-01",
 *     parentId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1",
 *     name: "vnet1",
 * });
 * export const vnetId = vnet.then(vnet => vnet.id);
 * export const vnetResourceGroup = vnet.then(vnet => vnet.resourceGroupName);
 * export const vnetSubscription = vnet.then(vnet => vnet.subscriptionId);
 * ```
 */
export function getResourceId(args: GetResourceIdArgs, opts?: pulumi.InvokeOptions): Promise<GetResourceIdResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("azapi:index/getResourceId:getResourceId", {
        "name": args.name,
        "parentId": args.parentId,
        "resourceId": args.resourceId,
        "timeouts": args.timeouts,
        "type": args.type,
    }, opts);
}

/**
 * A collection of arguments for invoking getResourceId.
 */
export interface GetResourceIdArgs {
    name?: string;
    parentId?: string;
    resourceId?: string;
    timeouts?: inputs.GetResourceIdTimeouts;
    type: string;
}

/**
 * A collection of values returned by getResourceId.
 */
export interface GetResourceIdResult {
    readonly id: string;
    readonly name: string;
    readonly parentId: string;
    readonly parts: {[key: string]: string};
    readonly providerNamespace: string;
    readonly resourceGroupName: string;
    readonly resourceId: string;
    readonly subscriptionId: string;
    readonly timeouts?: outputs.GetResourceIdTimeouts;
    readonly type: string;
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as azapi from "@pulumi/azapi";
 *
 * const account = azapi.getResourceId({
 *     type: "Microsoft.Automation/automationAccounts@2021-06-22",
 *     resourceId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1/providers/Microsoft.Automation/automationAccounts/automationAccount1",
 * });
 * export const accountName = account.then(account => account.name);
 * export const accountResourceGroup = account.then(account => account.resourceGroupName);
 * export const accountSubscription = account.then(account => account.subscriptionId);
 * export const accountParentId = account.then(account => account.parentId);
 * const vnet = azapi.getResourceId({
 *     type: "Microsoft.Network/virtualNetworks@2021-02-01",
 *     parentId: "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg1",
 *     name: "vnet1",
 * });
 * export const vnetId = vnet.then(vnet => vnet.id);
 * export const vnetResourceGroup = vnet.then(vnet => vnet.resourceGroupName);
 * export const vnetSubscription = vnet.then(vnet => vnet.subscriptionId);
 * ```
 */
export function getResourceIdOutput(args: GetResourceIdOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetResourceIdResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("azapi:index/getResourceId:getResourceId", {
        "name": args.name,
        "parentId": args.parentId,
        "resourceId": args.resourceId,
        "timeouts": args.timeouts,
        "type": args.type,
    }, opts);
}

/**
 * A collection of arguments for invoking getResourceId.
 */
export interface GetResourceIdOutputArgs {
    name?: pulumi.Input<string>;
    parentId?: pulumi.Input<string>;
    resourceId?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.GetResourceIdTimeoutsArgs>;
    type: pulumi.Input<string>;
}
