// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * This resource can access any existing Azure resource manager resource.## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as azapi from "@pulumi/azapi";
 * import * as azure from "@pulumi/azure";
 *
 * const exampleResourceGroup = new azure.core.ResourceGroup("exampleResourceGroup", {location: "west europe"});
 * const exampleRegistry = new azure.containerservice.Registry("exampleRegistry", {
 *     resourceGroupName: exampleResourceGroup.name,
 *     location: exampleResourceGroup.location,
 *     sku: "Premium",
 *     adminEnabled: false,
 * });
 * const exampleResource = azapi.getResourceOutput({
 *     name: "example",
 *     parentId: exampleResourceGroup.id,
 *     type: "Microsoft.ContainerRegistry/registries@2020-11-01-preview",
 *     responseExportValues: [
 *         "properties.loginServer",
 *         "properties.policies.quarantinePolicy.status",
 *     ],
 * });
 * export const loginServer = exampleResource.apply(exampleResource => exampleResource.output?.properties?.loginServer);
 * export const quarantinePolicy = exampleResource.apply(exampleResource => exampleResource.output?.properties?.policies?.quarantinePolicy?.status);
 * ```
 */
export function getResource(args: GetResourceArgs, opts?: pulumi.InvokeOptions): Promise<GetResourceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("azapi:index/getResource:getResource", {
        "headers": args.headers,
        "name": args.name,
        "parentId": args.parentId,
        "queryParameters": args.queryParameters,
        "resourceId": args.resourceId,
        "responseExportValues": args.responseExportValues,
        "retry": args.retry,
        "timeouts": args.timeouts,
        "type": args.type,
    }, opts);
}

/**
 * A collection of arguments for invoking getResource.
 */
export interface GetResourceArgs {
    headers?: {[key: string]: string};
    name?: string;
    parentId?: string;
    queryParameters?: {[key: string]: string[]};
    resourceId?: string;
    responseExportValues?: any;
    retry?: inputs.GetResourceRetry;
    timeouts?: inputs.GetResourceTimeouts;
    type: string;
}

/**
 * A collection of values returned by getResource.
 */
export interface GetResourceResult {
    readonly headers?: {[key: string]: string};
    readonly id: string;
    readonly identities: outputs.GetResourceIdentity[];
    readonly location: string;
    readonly name: string;
    readonly output: any;
    readonly parentId: string;
    readonly queryParameters?: {[key: string]: string[]};
    readonly resourceId: string;
    readonly responseExportValues?: any;
    readonly retry?: outputs.GetResourceRetry;
    readonly tags: {[key: string]: string};
    readonly timeouts?: outputs.GetResourceTimeouts;
    readonly type: string;
}
/**
 * This resource can access any existing Azure resource manager resource.## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as azapi from "@pulumi/azapi";
 * import * as azure from "@pulumi/azure";
 *
 * const exampleResourceGroup = new azure.core.ResourceGroup("exampleResourceGroup", {location: "west europe"});
 * const exampleRegistry = new azure.containerservice.Registry("exampleRegistry", {
 *     resourceGroupName: exampleResourceGroup.name,
 *     location: exampleResourceGroup.location,
 *     sku: "Premium",
 *     adminEnabled: false,
 * });
 * const exampleResource = azapi.getResourceOutput({
 *     name: "example",
 *     parentId: exampleResourceGroup.id,
 *     type: "Microsoft.ContainerRegistry/registries@2020-11-01-preview",
 *     responseExportValues: [
 *         "properties.loginServer",
 *         "properties.policies.quarantinePolicy.status",
 *     ],
 * });
 * export const loginServer = exampleResource.apply(exampleResource => exampleResource.output?.properties?.loginServer);
 * export const quarantinePolicy = exampleResource.apply(exampleResource => exampleResource.output?.properties?.policies?.quarantinePolicy?.status);
 * ```
 */
export function getResourceOutput(args: GetResourceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetResourceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("azapi:index/getResource:getResource", {
        "headers": args.headers,
        "name": args.name,
        "parentId": args.parentId,
        "queryParameters": args.queryParameters,
        "resourceId": args.resourceId,
        "responseExportValues": args.responseExportValues,
        "retry": args.retry,
        "timeouts": args.timeouts,
        "type": args.type,
    }, opts);
}

/**
 * A collection of arguments for invoking getResource.
 */
export interface GetResourceOutputArgs {
    headers?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    name?: pulumi.Input<string>;
    parentId?: pulumi.Input<string>;
    queryParameters?: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>}>;
    resourceId?: pulumi.Input<string>;
    responseExportValues?: any;
    retry?: pulumi.Input<inputs.GetResourceRetryArgs>;
    timeouts?: pulumi.Input<inputs.GetResourceTimeoutsArgs>;
    type: pulumi.Input<string>;
}
