// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * This resource can manage a subset of any existing Azure resource manager resource's properties.
 *
 * > **Note** This resource is used to add or modify properties on an existing resource.
 * When delete `azapi.UpdateResource`, no operation will be performed, and these properties will stay unchanged.
 * If you want to restore the modified properties to some values, you must apply the restored properties before deleting.
 *
 * ## Example Usage
 */
export class UpdateResource extends pulumi.CustomResource {
    /**
     * Get an existing UpdateResource resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UpdateResourceState, opts?: pulumi.CustomResourceOptions): UpdateResource {
        return new UpdateResource(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'azapi:index/updateResource:UpdateResource';

    /**
     * Returns true if the given object is an instance of UpdateResource.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is UpdateResource {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === UpdateResource.__pulumiType;
    }

    /**
     * A JSON object that contains the request body used to add on an existing azure resource.
     */
    public readonly body!: pulumi.Output<string | undefined>;
    /**
     * Whether ignore incorrect casing returned in `body` to suppress plan-diff. Defaults to `false`.
     */
    public readonly ignoreCasing!: pulumi.Output<boolean | undefined>;
    /**
     * Whether ignore not returned properties like credentials in `body` to suppress plan-diff. Defaults to `true`.
     */
    public readonly ignoreMissingProperty!: pulumi.Output<boolean | undefined>;
    /**
     * A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
     */
    public readonly locks!: pulumi.Output<string[] | undefined>;
    /**
     * Specifies the name of the azure resource. Changing this forces a new resource to be created.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The output json containing the properties specified in `responseExportValues`. Here're some examples to decode json and extract the value.
     * ```
     * // it will output "registry1.azurecr.io"
     * output "loginServer" {
     * value = jsondecode(azapi_resource.example.output).properties.loginServer
     * }
     */
    public /*out*/ readonly output!: pulumi.Output<string>;
    /**
     * The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created. It supports different kinds of deployment scope for **top level** resources: 
     * - resource group scope: `parentId` should be the ID of a resource group, it's recommended to manage a resource group by azurerm_resource_group.
     * - management group scope: `parentId` should be the ID of a management group, it's recommended to manage a management group by azurerm_management_group.
     * - extension scope: `parentId` should be the ID of the resource you're adding the extension to.
     * - subscription scope: `parentId` should be like `/subscriptions/00000000-0000-0000-0000-000000000000`
     * - tenant scope: `parentId` should be `/`
     *
     * For child level resources, the `parentId` should be the ID of its parent resource, for example, subnet resource's `parentId` is the ID of the vnet.
     */
    public readonly parentId!: pulumi.Output<string>;
    /**
     * The ID of an existing azure source. Changing this forces a new azure resource to be created.
     *
     * > **Note:** Configuring `name` and `parentId` is an alternative way to configure `resourceId`.
     */
    public readonly resourceId!: pulumi.Output<string>;
    /**
     * A list of path that needs to be exported from response body.
     * Setting it to `["*"]` will export the full response body.
     * Here's an example. If it sets to `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following json to computed property `output`.
     * ```
     * {
     * "properties" : {
     * "loginServer" : "registry1.azurecr.io"
     * "policies" : {
     * "quarantinePolicy" = {
     * "status" = "disabled"
     * }
     * }
     * }
     * }
     * ```
     */
    public readonly responseExportValues!: pulumi.Output<string[] | undefined>;
    /**
     * It is in a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
     * `<api-version>` is version of the API used to manage this azure resource.
     */
    public readonly type!: pulumi.Output<string>;

    /**
     * Create a UpdateResource resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UpdateResourceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UpdateResourceArgs | UpdateResourceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UpdateResourceState | undefined;
            resourceInputs["body"] = state ? state.body : undefined;
            resourceInputs["ignoreCasing"] = state ? state.ignoreCasing : undefined;
            resourceInputs["ignoreMissingProperty"] = state ? state.ignoreMissingProperty : undefined;
            resourceInputs["locks"] = state ? state.locks : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["output"] = state ? state.output : undefined;
            resourceInputs["parentId"] = state ? state.parentId : undefined;
            resourceInputs["resourceId"] = state ? state.resourceId : undefined;
            resourceInputs["responseExportValues"] = state ? state.responseExportValues : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as UpdateResourceArgs | undefined;
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["body"] = args ? args.body : undefined;
            resourceInputs["ignoreCasing"] = args ? args.ignoreCasing : undefined;
            resourceInputs["ignoreMissingProperty"] = args ? args.ignoreMissingProperty : undefined;
            resourceInputs["locks"] = args ? args.locks : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["parentId"] = args ? args.parentId : undefined;
            resourceInputs["resourceId"] = args ? args.resourceId : undefined;
            resourceInputs["responseExportValues"] = args ? args.responseExportValues : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["output"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(UpdateResource.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering UpdateResource resources.
 */
export interface UpdateResourceState {
    /**
     * A JSON object that contains the request body used to add on an existing azure resource.
     */
    body?: pulumi.Input<string>;
    /**
     * Whether ignore incorrect casing returned in `body` to suppress plan-diff. Defaults to `false`.
     */
    ignoreCasing?: pulumi.Input<boolean>;
    /**
     * Whether ignore not returned properties like credentials in `body` to suppress plan-diff. Defaults to `true`.
     */
    ignoreMissingProperty?: pulumi.Input<boolean>;
    /**
     * A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
     */
    locks?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Specifies the name of the azure resource. Changing this forces a new resource to be created.
     */
    name?: pulumi.Input<string>;
    /**
     * The output json containing the properties specified in `responseExportValues`. Here're some examples to decode json and extract the value.
     * ```
     * // it will output "registry1.azurecr.io"
     * output "loginServer" {
     * value = jsondecode(azapi_resource.example.output).properties.loginServer
     * }
     */
    output?: pulumi.Input<string>;
    /**
     * The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created. It supports different kinds of deployment scope for **top level** resources: 
     * - resource group scope: `parentId` should be the ID of a resource group, it's recommended to manage a resource group by azurerm_resource_group.
     * - management group scope: `parentId` should be the ID of a management group, it's recommended to manage a management group by azurerm_management_group.
     * - extension scope: `parentId` should be the ID of the resource you're adding the extension to.
     * - subscription scope: `parentId` should be like `/subscriptions/00000000-0000-0000-0000-000000000000`
     * - tenant scope: `parentId` should be `/`
     *
     * For child level resources, the `parentId` should be the ID of its parent resource, for example, subnet resource's `parentId` is the ID of the vnet.
     */
    parentId?: pulumi.Input<string>;
    /**
     * The ID of an existing azure source. Changing this forces a new azure resource to be created.
     *
     * > **Note:** Configuring `name` and `parentId` is an alternative way to configure `resourceId`.
     */
    resourceId?: pulumi.Input<string>;
    /**
     * A list of path that needs to be exported from response body.
     * Setting it to `["*"]` will export the full response body.
     * Here's an example. If it sets to `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following json to computed property `output`.
     * ```
     * {
     * "properties" : {
     * "loginServer" : "registry1.azurecr.io"
     * "policies" : {
     * "quarantinePolicy" = {
     * "status" = "disabled"
     * }
     * }
     * }
     * }
     * ```
     */
    responseExportValues?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * It is in a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
     * `<api-version>` is version of the API used to manage this azure resource.
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a UpdateResource resource.
 */
export interface UpdateResourceArgs {
    /**
     * A JSON object that contains the request body used to add on an existing azure resource.
     */
    body?: pulumi.Input<string>;
    /**
     * Whether ignore incorrect casing returned in `body` to suppress plan-diff. Defaults to `false`.
     */
    ignoreCasing?: pulumi.Input<boolean>;
    /**
     * Whether ignore not returned properties like credentials in `body` to suppress plan-diff. Defaults to `true`.
     */
    ignoreMissingProperty?: pulumi.Input<boolean>;
    /**
     * A list of ARM resource IDs which are used to avoid create/modify/delete azapi resources at the same time.
     */
    locks?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Specifies the name of the azure resource. Changing this forces a new resource to be created.
     */
    name?: pulumi.Input<string>;
    /**
     * The ID of the azure resource in which this resource is created. Changing this forces a new resource to be created. It supports different kinds of deployment scope for **top level** resources: 
     * - resource group scope: `parentId` should be the ID of a resource group, it's recommended to manage a resource group by azurerm_resource_group.
     * - management group scope: `parentId` should be the ID of a management group, it's recommended to manage a management group by azurerm_management_group.
     * - extension scope: `parentId` should be the ID of the resource you're adding the extension to.
     * - subscription scope: `parentId` should be like `/subscriptions/00000000-0000-0000-0000-000000000000`
     * - tenant scope: `parentId` should be `/`
     *
     * For child level resources, the `parentId` should be the ID of its parent resource, for example, subnet resource's `parentId` is the ID of the vnet.
     */
    parentId?: pulumi.Input<string>;
    /**
     * The ID of an existing azure source. Changing this forces a new azure resource to be created.
     *
     * > **Note:** Configuring `name` and `parentId` is an alternative way to configure `resourceId`.
     */
    resourceId?: pulumi.Input<string>;
    /**
     * A list of path that needs to be exported from response body.
     * Setting it to `["*"]` will export the full response body.
     * Here's an example. If it sets to `["properties.loginServer", "properties.policies.quarantinePolicy.status"]`, it will set the following json to computed property `output`.
     * ```
     * {
     * "properties" : {
     * "loginServer" : "registry1.azurecr.io"
     * "policies" : {
     * "quarantinePolicy" = {
     * "status" = "disabled"
     * }
     * }
     * }
     * }
     * ```
     */
    responseExportValues?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * It is in a format like `<resource-type>@<api-version>`. `<resource-type>` is the Azure resource type, for example, `Microsoft.Storage/storageAccounts`.
     * `<api-version>` is version of the API used to manage this azure resource.
     */
    type: pulumi.Input<string>;
}
